pranjay-poddar/Dev-Geeks

Js-Games/Fall Game/index.html
Js-Games/Fall Game/script.js
Js-Games/Fall Game/style.css

Added a Fall n Down Game built with JavaScript.

Added Fall Game

---

Js-Projects/QR-Code-Generator/index.html

Added a QR Code generator using JavaScript

✨ Add QR Code Generator

---

Js-Projects/digital clock/README.md
Js-Projects/digital clock/index.html

A digital clock using HTML , CSS , JS.
completed #129

Added a digital clock

---

Js-Games/Tetris Game JS/index.html
Js-Games/Tetris Game JS/instructions.html
Js-Games/Tetris Game JS/script.js
Js-Games/Tetris Game JS/style.css
Js-Games/Tetris Game JS/tetris.html

**Technology Stack :** 
- HTML5
- CSS3
- JavaScript 
Features : 
- main home page
- instructions page
- tetris game page
- interactive and simple to use

Simple Tetris Game made using HTML, CSS and JavaScript

---

Frontend-Projects/simple to do list/index.html
Frontend-Projects/simple to do list/script.js
Frontend-Projects/simple to do list/style.css

Tech stack :
HTML
CSS
JavaScript
Expected behaviour : 
User can add , delete and update tasks for daily needs with a simple interface.
Screenshots : 
Details : 
A simple web application that can be operated on any device without any installations . A lightweight application.

simple to do list for daily tasks

---

Js-Projects/Text to speech/README.md
Js-Projects/Text to speech/index.html
Js-Projects/Text to speech/script.js
Js-Projects/Text to speech/style.css

text to speech converter a java script based project.
completed #169

text to speech converter 

---

Frontend-Projects/simple calculator/index.html
Frontend-Projects/simple calculator/readme.md
Frontend-Projects/simple calculator/script.js
Frontend-Projects/simple calculator/style.css

Made this simple calculator using html, css and js.

Added my simple calculator.

---

Js-Projects/stopwatch js/index.html
Js-Projects/stopwatch js/script.js
Js-Projects/stopwatch js/style.css

Project name : Stopwatch
A simple project made using javascript, html / css .
components included : 
- start timer
- stop timer
- reset timer
Available in only dark mode

added a js project

---

Frontend-Projects/signup form/index.html
Frontend-Projects/signup form/login.html
Frontend-Projects/signup form/readme.md
Frontend-Projects/signup form/signin.html
Frontend-Projects/signup form/style.css

Added my functional sign up page.

Added my sign up page

---

Frontend-Projects/responsive footer/index.html
Frontend-Projects/responsive footer/readme.md
Frontend-Projects/responsive footer/style.css

My fully responsive footer website with all clickable links made using html and css.

Added my responsive footer.

---

Frontend-Projects/SIGN UP FORM/README.md
Frontend-Projects/SIGN UP FORM/index.html
Frontend-Projects/SIGN UP FORM/style.css

SIGNUP FORM
A simple sign up form is created and validation is done with JavaScript.
Authors
@Nirvik07

Signup Form #9

---

Js-Games/Lizard Spock Game/README.md
Js-Games/Lizard Spock Game/confetti.js
Js-Games/Lizard Spock Game/index.html
Js-Games/Lizard Spock Game/main.js
Js-Games/Lizard Spock Game/style.css

Closes #180 
https://user-images.githubusercontent.com/73753957/180050749-8cfe0996-0f85-4f7a-a0f0-863a09079fc6.mp4

Lizard Spock game Added

---

Js-Projects/Random hex generator/README.md
Js-Projects/Random hex generator/index.html
Js-Projects/Random hex generator/script.js
Js-Projects/Random hex generator/style.css

Random hex color code generator in HTML, CSS and mostly JS .
closes #191

random hex generator

---

Navbars/Responsive Navbar with Animation/app.js
Navbars/Responsive Navbar with Animation/circles.svg
Navbars/Responsive Navbar with Animation/index.html
Navbars/Responsive Navbar with Animation/style.css

Issue no #36 
I have created a nav-bar which is responsive for Larger(computers), Medium(tablets) as well as Smaller(Mobile) level displays 
the **nav-bar besides being responsive, is also animated** when one clicks on hamburger menu

Added Responsive NavBar Project

---

ML Projects/word to pdf/.idea/.gitignore
ML Projects/word to pdf/.idea/inspectionProfiles/Project_Default.xml
ML Projects/word to pdf/.idea/inspectionProfiles/profiles_settings.xml
ML Projects/word to pdf/.idea/misc.xml
ML Projects/word to pdf/.idea/modules.xml
ML Projects/word to pdf/.idea/word to pdf.iml
ML Projects/word to pdf/README.md
ML Projects/word to pdf/main.py

Word to pdf converter in python.
closes #226 
kindly check README for demonstration.

Added word to pdf converter

---

ML Projects/Text File Analysis/main.py

Text File Analysis

---

ML Projects/WhatsApp Bot/main.py

WhatsApp Bot

---

ML Projects/Weather-teller/.idea/.gitignore
ML Projects/Weather-teller/.idea/inspectionProfiles/Project_Default.xml
ML Projects/Weather-teller/.idea/inspectionProfiles/profiles_settings.xml
ML Projects/Weather-teller/.idea/misc.xml
ML Projects/Weather-teller/.idea/modules.xml
ML Projects/Weather-teller/.idea/project dev.iml
ML Projects/Weather-teller/README.md
ML Projects/Weather-teller/main.py

Added weather telling program written in python. 
closes #210 
for demonstration please check README file.

Added weather-teller

---

ML Projects/Reduce Image Size/reduce.py

Image Reducer

---

Js-Projects/Volume Calculator/CSS/style.css
Js-Projects/Volume Calculator/JS/jsfile.js
Js-Projects/Volume Calculator/index.html

Fix Issue #240 Added a volume Calculator

---

ML Projects/png or jpeg to pdf/.idea/.gitignore
ML Projects/png or jpeg to pdf/.idea/inspectionProfiles/Project_Default.xml
ML Projects/png or jpeg to pdf/.idea/inspectionProfiles/profiles_settings.xml
ML Projects/png or jpeg to pdf/.idea/misc.xml
ML Projects/png or jpeg to pdf/.idea/modules.xml
ML Projects/png or jpeg to pdf/.idea/png or jpeg to pdf.iml
ML Projects/png or jpeg to pdf/README.md
ML Projects/png or jpeg to pdf/main.py

added python project.
closes #249

added png/jpeg to pdf converter.

---

ML Projects/PDF to TXT/Converter.py

PDF to TXT

---

ML Projects/Browser/README.md
ML Projects/Browser/main.py

Added browser made in python.
closes #268

Added browser

---

ML Projects/Youtube-video-downloader/.idea/.gitignore
ML Projects/Youtube-video-downloader/.idea/inspectionProfiles/Project_Default.xml
ML Projects/Youtube-video-downloader/.idea/inspectionProfiles/profiles_settings.xml
ML Projects/Youtube-video-downloader/.idea/misc.xml
ML Projects/Youtube-video-downloader/.idea/modules.xml
ML Projects/Youtube-video-downloader/.idea/yt do.iml
ML Projects/Youtube-video-downloader/README.md
ML Projects/Youtube-video-downloader/main.py

Added a python project.
closes #253 
Demonstration -
https://user-images.githubusercontent.com/91176055/181054096-167b113e-a305-4459-a401-0f422f05a258.mp4

added youtube video downloader

---

Python Projects/Number Guessing Game.py

Closes #284

---

Js-Games/loveCalculater website/index.html
Js-Games/loveCalculater website/index.js
Js-Games/loveCalculater website/style.css

added love-calculator-website.

love-calculator-website

---

Js-Projects/Number Guessing Game/index.html
Js-Projects/Number Guessing Game/script.js
Js-Projects/Number Guessing Game/style.css

Number Using Game

---

Js-Games/Insect_Catching_Game/index.html
Js-Games/Insect_Catching_Game/script.js
Js-Games/Insect_Catching_Game/style.css

Adding Insect Catching Game

---

ML Projects/Demerging PDF/main.py

It closes the Issue : #312 
https://user-images.githubusercontent.com/77090462/181752242-f3da630c-b023-4851-a023-f754ff3657a1.mov

DeMerging PDF

---

ML Projects/AI Tic Tac Toe/main.py

IT closes the issue : #313
https://user-images.githubusercontent.com/77090462/181753205-05a484e1-74b9-4132-b5d3-e123ff66a36c.mov

AI Tic Tac Toe

---

ML Projects/GUI calculator/.idea/.gitignore
ML Projects/GUI calculator/.idea/New folder.iml
ML Projects/GUI calculator/.idea/inspectionProfiles/Project_Default.xml
ML Projects/GUI calculator/.idea/inspectionProfiles/profiles_settings.xml
ML Projects/GUI calculator/.idea/misc.xml
ML Projects/GUI calculator/.idea/modules.xml
ML Projects/GUI calculator/README.md
ML Projects/GUI calculator/main.py

GUI calculator using python
closes #328 
https://user-images.githubusercontent.com/91176055/181757483-a9514454-b23b-44de-a13d-79fa8e5067a1.mp4

Added GUI calculator

---

ML Projects/Customer_loan_repayment_problem/datasets_137197_325031_test_Y3wMUE5_7gLdaTN.csv
ML Projects/Customer_loan_repayment_problem/loan-prediction-problem.ipynb

It closes the issue #316 
Here is the link of the [folder](https://github.com/Avik-creator/Dev-Geeks/tree/Customer-Loan-Prediction/ML%20Projects/Customer_loan_repayment_problem)

Customer Loan Prediction

---

Python Projects/WarCardGame.py

WAR Card Game

---

Js-Projects/Number_of_Days_Calculator/app.js
Js-Projects/Number_of_Days_Calculator/index.html
Js-Projects/Number_of_Days_Calculator/style.css

Adding Number of Days Calculator

---

Js-Games/Typer/README.md
Js-Games/Typer/canvas.js
Js-Games/Typer/index.html
Js-Games/Typer/particle.js
Js-Games/Typer/typer.css
Js-Games/Typer/typer.js

Adding Typer Game

---

Js-Projects/3D_Sapes_Volume_Calculator/index.html
Js-Projects/3D_Sapes_Volume_Calculator/script.js
Js-Projects/3D_Sapes_Volume_Calculator/style.css

ADDING 3D SHAPES VOLUME CALC

---

Monty-Hall-Problem-Simulation/app.py

Monty Hall Problem Solutions

---

Animations-CSS/Countdown_Animation/app.js
Animations-CSS/Countdown_Animation/index.html
Animations-CSS/Countdown_Animation/style.css

Adding Project Countdown Animation

---

ML Projects/Compress PDF'S/compress.py

PDF Compressor

---

Frontend-Projects/Hoverboard/index.html
Frontend-Projects/Hoverboard/script.js
Frontend-Projects/Hoverboard/style.css

Adding Project Hoverboard

---

ML Projects/Plagiarism Checker/README.md
ML Projects/Plagiarism Checker/main.py
Plagiarism Checker/main.py

Plagiarism checker

---

Js-Games/loveCalculater website/index.html
Js-Games/loveCalculater website/style.css
Js-Projects/notes app/index.html

I have updated the elements of Love Calculator which closes the issue number #387

Updated Love Calculator

---

Java Projects/Currency/converter.java

Currency Converter

---

ML Projects/Tic Tac Toe/main.py

Tic Tac Toe

---

Js-Games/breakout game/index.html
Js-Games/breakout game/script.js
Js-Games/breakout game/style.css

This completes and closes #336 
**Tech Stack used**  : HTML, CSS & JS
simple breakout game to move in js games folder
**Screenshots** :

Breakout Game

---

Python Projects/main.py

This completes and closes #401 
**Tech stack used**
Python and its fpdf module
**Working**
A simple reciept generator for usage in markets and shops. Here the user will enter the product name, product code, quantity bought and unit price . The program will then print a reciept in pdf form which will be given to the user.

Reciept Generator made using python

---

Frontend-Projects/Gym website/index.html

made changes in font style ans sizes

Updated apna gym

---

Frontend-Projects/responsive navbar/index.html
Frontend-Projects/responsive navbar/style.css

responsive navbar

---

Python Projects/Blackjack.py

**Blackjack Python Game**
A simple single player blackjack game that runs in the terminal (no GUI) developed in Python.
The project simulates the famous Blackjack game. The game starts and the player receives a random card, after that the player can request another card or stop the game. The objective is to score as many points as possible without exceeding 21 points.
The Jack, Queen and King cards are 10 points.
The Ace card can be 1 or 10 points, depending on player choice.
The other cards (2, 3, 4, ..., 9) have the value of the number they have.
**Tech**
Python
**Issue**
Issue: https://github.com/pranjay-poddar/Dev-Geeks/issues/442
Authors
[@ViniciusMarchi](https://github.com/ViniciusMarchi)

Blackjack python game

---

Node-JS Projects/Tech-News API/.gitignore
Node-JS Projects/Tech-News API/README.md
Node-JS Projects/Tech-News API/index.js
Node-JS Projects/Tech-News API/package-lock.json
Node-JS Projects/Tech-News API/package.json

Tech-News API

---

Footers/content-footer/index.html

Add javascript to update copyright every year

Add script to update Copyright year

---

Js-Projects/Canvas_Drawing_Tool/index.html
Js-Projects/Canvas_Drawing_Tool/main.js
Js-Projects/Canvas_Drawing_Tool/readme.md
Js-Projects/Canvas_Drawing_Tool/style.css

@pranjay-poddar Please review my pull request and merge it

Canvas drawing tool added

---

Python Projects/Snake Game/snakegame.py

This closes issue #446.
A snake game using python and pygame library. 
Screenshots -

Snake Game added

---

Js-Projects/age-calculator/age_calculator.js

Created Age Calculator.
You enter the date of birth and it tell you how many years are you. I hope you like this program.
Please if it is okay for you, could you put the hacktoberfest or hacktoberfest accepted label? Thank you so much for the opportunity to contribute!!

Created Age Calculator

---

Frontend-Projects/Login & Sign-Up/index.html
Frontend-Projects/Login & Sign-Up/readme.md
Frontend-Projects/Login & Sign-Up/signUp.html

Close #6   Add Frontend Project

Login & Sign Up form added by wizeewig

---

Node-JS Projects/To-Do-List/README.md
Node-JS Projects/To-Do-List/index.html
Node-JS Projects/To-Do-List/index.js
Node-JS Projects/To-Do-List/package-lock.json
Node-JS Projects/To-Do-List/package.json
Node-JS Projects/To-Do-List/styles.css

To-Do-List

---

Python Projects/2048/README.md
Python Projects/2048/func.py
Python Projects/2048/main.py

2048 game in Python

---

Frontend-Projects/TV Show Search WebApp/README.md
Frontend-Projects/TV Show Search WebApp/index.html
Frontend-Projects/TV Show Search WebApp/tvshow.css
Frontend-Projects/TV Show Search WebApp/tvshow.js

Close #532
Added tv show search website where user can search for any tv show.
Built using HTML, CSS and JavaScript and it is also responsive.
Screenshots

Added Tv Show Search WebApp

---

Js-Games/dicegame/index.css
Js-Games/dicegame/index.html
Js-Games/dicegame/script.js

Dice game using html, CSS and JavaScript 

---

Frontend-Projects/registration form/index.html
Frontend-Projects/registration form/readme.md
Frontend-Projects/registration form/styles.css

Added a form page (Registration Form)
Close #558

Added a Registration Form

---

Js-Projects/Digital_Clock/clock.js
Js-Projects/Digital_Clock/index.html
Js-Projects/Digital_Clock/styles.css

updated digital clock

---

Js-Projects/AdBlocker/README.md
Js-Projects/AdBlocker/index.html
Js-Projects/AdBlocker/script.js

Ad blocker

---

Frontend-Projects/Registration Form for Driving License/Driving License Registration Form.html

Registration Page for Applying for Driver's License #579 
Close #579 

Registration Form for Driver's License

---

Animations-CSS/Curved Carousel/index.html
Animations-CSS/Curved Carousel/style.css

Added curved carousel in animation CSS. 
Close #588

Added curved carousel 

---

Python Projects/Random Story Generator/random_story_generator.py

Random Story Generator (Python program). Issue #629 
Close #629 
-

Add random_story_generator.py

---

Python Projects/dice_sim.py

Dice Simulator #615
Close #615

Dice Simulator

---

Footers/footer/index.html
Footers/footer/style.css

I built the mobile design of the footer and made it responsive.
Close #60

Created the mobile design of the footer

---

Js-Projects/Digital_Clock/README.md

Digital Clock with Js #557 
Close #557

Updated README.md

---

Js-Projects/Neon number/index.html
Js-Projects/Neon number/script.js
Js-Projects/Neon number/style.css

Neon Number Checker

---

Python Projects/Timer/main.py

- [yes] I have mentioned the issue number in my Pull Request.
- [not necessary] I have commented my code, particularly in hard-to-understand areas
- [no] I have created a helpful and easy to understand `README.md`

Made a Timer Using Tkinter and Python

---

README.md

All the projects updated till 07 Oct, 2022

---

ML Projects/Analysis of Fashion_dataset/Fashion dataset.ipynb
ML Projects/Analysis of Fashion_dataset/README.md
README.md

Analysis and Prediction of the Keras fashion dataset using various deep learning models #696 
Close #696

Analysis and Prediction of the keras fashion dataset using various deep learning models

---

Js-Projects/FAQ Collapse/README.md
Js-Projects/FAQ Collapse/index.html
Js-Projects/FAQ Collapse/script.js
Js-Projects/FAQ Collapse/style.css

#641 - FAQ collapse project
Close #641 

FAQ COLLAPSE

---

Js-Projects/js-clock/Readme.md
Js-Projects/js-clock/index.html
Js-Projects/js-clock/main.js
Js-Projects/js-clock/style.css

Add JavaScript Clock

---

Frontend-Projects/simple calculator/index.html
Frontend-Projects/simple calculator/script.js

Signed-off-by: Srihari S <sshsrn@gmail.com>
Key Press Functionality for Front end Calculator Project #806
Close #806

Add key press functionality for Front-end calculator project

---

Frontend-Projects/Notes_App/index.html
Frontend-Projects/Notes_App/script.js
Frontend-Projects/Notes_App/style.css
Js-Projects/Notes_App/index.html
Js-Projects/Notes_App/script.js
Js-Projects/Notes_App/style.css

Simple Notes app - issue no #671
Close #671

Simple Notes App

---

Animations-CSS/Bulbasaur-Button/Readme.md
Animations-CSS/Bulbasaur-Button/index.css
Animations-CSS/Bulbasaur-Button/index.html

Bulbasaur-Button and Issue Number-#722
Close #722

Bulbasaur button

---

Animations-CSS/search-toggle/index.html
Animations-CSS/search-toggle/script.js
Animations-CSS/search-toggle/style.css

A search toggle animated using css and a bit of js.
Close #732 

Added search toggle on animations-css

---

Python Projects/.py to .apk/README.md
Python Projects/.py to .apk/main.py

Title - .py to .apk project
Issue no.- #763 
Close #763

Added .py to .apk project with documentation

---

Python Projects/VirtualCalculator/.idea/.gitignore
Python Projects/VirtualCalculator/.idea/VirtualCalculator.iml
Python Projects/VirtualCalculator/.idea/inspectionProfiles/Project_Default.xml
Python Projects/VirtualCalculator/.idea/inspectionProfiles/profiles_settings.xml
Python Projects/VirtualCalculator/.idea/misc.xml
Python Projects/VirtualCalculator/.idea/modules.xml
Python Projects/VirtualCalculator/M.py
Python Projects/VirtualCalculator/main.py

IT IS A COMPUTER VISION PROJECT WHICH TRACKS HAND MOVEMENT TO SELECT OPERANDS AND OPERATIONS AND EXECUTES THE EXPRESSION
Close #788

Virtual Calculator using Python added #788

---

Js-Games/Country Guesser/Readme.md
Js-Games/Country Guesser/index.html
Js-Games/Country Guesser/main.js

Add Country Guesser Game in JavaScript

---

Js-Projects/Hex color generator/README.md
Js-Projects/Hex color generator/index.html
Js-Projects/Hex color generator/script.js
Js-Projects/Hex color generator/style.css

#757 
Added Hex Color Generator
Close #757

HEX COLOR GENERATOR

---

Js-Projects/URL_Shrinker/Procfile
Js-Projects/URL_Shrinker/app.js
Js-Projects/URL_Shrinker/package-lock.json
Js-Projects/URL_Shrinker/package.json
Js-Projects/URL_Shrinker/views/index.ejs

URL_Shrinker(or Shortener)
https://github.com/pranjay-poddar/Dev-Geeks/issues/835
Close #835

URL_Shrinker(or Shortener)

---

Python Projects/Text-to-handwriting/README.md
Python Projects/Text-to-handwriting/main.py

Adding Text to Handwriting python program

---

Python Projects/Sudoku-Backtracking-Algo/README.md
Python Projects/Sudoku-Backtracking-Algo/main.py

Sudoku Solver using backtracking algo

---

Js-Projects/Simple-Library-Managment/index.html
Js-Projects/Simple-Library-Managment/readme.md
Js-Projects/Simple-Library-Managment/script.js

A simple library management project that is easy to use and helps learners understand the basic concept of JS. In this project, the user has a provision to add book details like book name, author name, and type through the web page. In addition to this, the user has a provision to search for the available books in the library by the book name or author name, or type. If book details are present in the LocalStorage, the search details are displayed on the web page. User has also a provision to delete a specific book or delete all books.
<p align="center">
</p>
Close  #890

Simple Library Management

---

Frontend-Projects/BeautifulTweets/Readme.md
Frontend-Projects/BeautifulTweets/index.html
Frontend-Projects/BeautifulTweets/style.css

Code for BeautifulTweets

---

React-JS Projects/Emojipedia/package.json
React-JS Projects/Emojipedia/public/index.html
React-JS Projects/Emojipedia/public/styles.css
React-JS Projects/Emojipedia/src/components/App.jsx
React-JS Projects/Emojipedia/src/components/Entry.jsx
React-JS Projects/Emojipedia/src/emojipedia.js
React-JS Projects/Emojipedia/src/index.js

Thank you for considering my pull request. I have added emojipedia using reactjs.

Add Emojipedia

---

Frontend-Projects/Restaurant site/CSS/style.css
Frontend-Projects/Restaurant site/about.html

change some style

---

Animations-CSS/3D rotating cube/README.md
Animations-CSS/3D rotating cube/index.html
Animations-CSS/3D rotating cube/styles.css
README.md

Issue #1247 Rotating 3D cube
Close #1247 
-

Rotating 3D Cube

---

Animations-CSS/text-glitch-effect/index.html
Animations-CSS/text-glitch-effect/style.css

Close #971
As a dedicated contributor to GSSOC'23, I'm excited to inform you that I have successfully added the eye-catching glitch effect to the project. 
I kindly request @pranjay-poddar  to close the review process and proceed with merging the pull request into the main branch. I have ensured that all necessary changes have been implemented and that the glitch effect seamlessly integrates with the existing codebase.
Your prompt attention to this matter is greatly appreciated. Thank you for providing me with the opportunity to contribute to GSSOC'23!

Text-Glitch-Effect Added

---

Frontend-Projects/Notes_App/index.html
Frontend-Projects/Notes_App/style.css

#1207 Add background image to notes

Add background image to notes

---

Animations-CSS/glowing-text-animation/index.html
Animations-CSS/glowing-text-animation/readme.md
Animations-CSS/glowing-text-animation/style.css

Glowing text animation #1252 
Close #1252

Glowing text animation 

---

Frontend-Projects/Dinosaur game/LandingPage.html
Frontend-Projects/Ecommerce Sneaker Website/index.html

Error showing on clicking Home in Ecommerce Sneaker Website [GSSoC'23]
#1595 
Close #1595 

Fixed Home page of Sneaker website

---

Frontend-Projects/Dinosaur game/LandingPage.html

Dinosaur game is not opening [GSSoC'23]
#1428
Close #1428  

Fixed URL of  Dinosaur game

---

Js-Games/README.md
Js-Games/index.css
Js-Games/index.html

Added Bird Game

---

React-JS Projects/quote-generator/README.md
React-JS Projects/quote-generator/src/App.css
React-JS Projects/quote-generator/src/App.js

React update

---

Js-Projects/Number_System_Converter/README.md
Js-Projects/Number_System_Converter/index.html
Js-Projects/Number_System_Converter/script.js
Js-Projects/Number_System_Converter/style.css

Close [#1647](https://github.com/pranjay-poddar/Dev-Geeks/issues/1647)

number system converter added

---

Java Projects/NumberGuessingGame/NumberGuessingGame.java
Java Projects/NumberGuessingGame/README.md

Add NumberGuessingGame

---

Frontend-Projects/fruit_website/index.html
Frontend-Projects/fruit_website/styles.css

Update the Shop Now button of the Fruit Website(Issue #1605)
Close #1605

Update the Shop Now button

---

Js-Projects/Notes__ App/index.html
Js-Projects/Notes__ App/script.js
Js-Projects/Notes__ App/styles.css

Added Notes__App to Js-Projects

---

Js-Games/Valorous_Rabbit/dist/index.html
Js-Games/Valorous_Rabbit/dist/script.js
Js-Games/Valorous_Rabbit/dist/style.css

Added a new game Valorous Rabbit in the JS-games file.
Valorous Rabbit Game #1531
Close #1531

Added a new game Valorous Rabbit

---

Frontend-Projects/Plankman/README.md
Frontend-Projects/Plankman/index.html
Frontend-Projects/Plankman/style.css
README.md

Add Plankman game

---

Python Projects/Gif Creator/readme

To add a Readme file for Gif Creator Python Project,  #1530
Close #1692
by merging this pull request

Added Readme file for Gif Creator

---

Navbars/responsive navbar/styles.css

change responsive navbar

---

Js-Projects/Background_Color_Change/index.html
Js-Projects/Background_Color_Change/readme.md
Js-Projects/Background_Color_Change/script.js
Js-Projects/Background_Color_Change/style.css

Background Color Change Issue 1543
Deployed Demo : https://shloksuman.github.io/bgcolorchange/
Close #1543

Background Color Change

---

Js-Games/Memory Game/index.html
Js-Games/Memory Game/script.js
Js-Games/Memory Game/style.css

To add a memory game #1660 
Close #1160

Adding memory game

---

Js-Projects/postman clone/Readme.md
Js-Projects/postman clone/index.html
Js-Projects/postman clone/script.js
Js-Projects/postman clone/styles.css

POSTMAN CLONE 

---

Frontend-Projects/Education website/mobile.html
Frontend-Projects/Education website/web-development.html

Blank page shown on clicking Products in Ecommerce Sneaker Website [GSSoC'23] #1598
Close #1598 

Fixed hyperlinks

---

Frontend-Projects/Apple Ecommerce/README.md
Frontend-Projects/Apple Ecommerce/index.html
Frontend-Projects/Apple Ecommerce/style.css

header and buttons

---

Js-Projects/Random password Generator/Readme.md
Js-Projects/Random password Generator/index.html
Js-Projects/Random password Generator/main.js
Js-Projects/Random password Generator/styles.css

Random Password Generator

---

Js-Projects/Graph Visuliser/README.md
Js-Projects/Graph Visuliser/index.html
Js-Projects/Graph Visuliser/script.js
Js-Projects/Graph Visuliser/style.css

added Graph Visualiser

---

ML Projects/Realtime Sign Language Detection System/PROJECT.ipynb
ML Projects/Realtime Sign Language Detection System/README.md

**Realtime Sign Language Detection System**: I have added this project into **_ML Projects_** Folder.
**Tech stack**: Tensorflow, Python, OpenCV, LSTM Deep Learning Model
Issue Number : #1824 
Close #1824

[Add] Realtime Sign Language Detection System | [GSSoC'23]

---

Js-Games/sokoban/index.html
Js-Games/sokoban/style.css

fix issue: #1736 
Project Description:
The goal is to navigate a warehouse maze and push all the boxes to their designated locations. The player controls a character within the maze and can move up, down, left, or right to push the boxes. The game is won when all the boxes are successfully pushed to their target positions.
Expected Behavior:
The game will start with a warehouse maze displayed on the screen. The player can use arrow keys or WASD keys to move the character around the maze. When the character encounters a box, they can push it in the direction they are facing if there is no obstruction. The player wins the game when all the boxes are pushed onto their designated target positions. Each successful box push will earn the player points.

[GSSoC'23] Add Sokoban Game

---

Js-Games/snake-water-gun game/README.md
Js-Games/snake-water-gun game/index.html
Js-Games/snake-water-gun game/script.js
Js-Games/snake-water-gun game/style.css

https://github.com/pranjay-poddar/Dev-Geeks/assets/120494269/1dc9098a-8d69-4171-902d-ab017320ca9f
Close #1831

snake water game added

---

Frontend-Projects/BeautifulTweets/Readme.md
Frontend-Projects/BeautifulTweets/index.html
Frontend-Projects/BeautifulTweets/style.css

Close #1754
I have added navbar in the website and also added dark mode functionality in the website.
screen recording
https://github.com/pranjay-poddar/Dev-Geeks/assets/103828217/63dd74c3-3799-448f-afc6-215dec08847f
New Feature Added.
1. Open the Website.
2. Click on the dark mode icon on the top right of the navbar.
Dark mode
Light mode

navbar with night mode

---

Animations-CSS/Distortion/index.html
Animations-CSS/Distortion/style.css

**Title and Issue number** 
Issues In Project: Animation-CSS -> Distortion 
Issue Number: #1439
Close #1439 
**Correction in index.html**
**Correction in style.css**
**A look of the webpage after implementation of the changes**:
https://github.com/pranjay-poddar/Dev-Geeks/assets/103258259/c0b46def-2902-470f-848f-f57aa91456b9

Spell Checks implemented and CSS enhanced

---

INDEXX.html
Readme
about.html
blog.html
cart.html
contact.html
index.html
script.js
shop.html
sproduct.html
sproduct2.html
style.css

https://github.com/pranjay-poddar/Dev-Geeks/assets/89354933/b33d61d7-63a4-4b51-8804-ff00c62bdac9
Close #1931
est.

Guess the color #1931

---

Js-Projects/Light_Dark_Mode_Calculator/README.md
Js-Projects/Light_Dark_Mode_Calculator/dark.css
Js-Projects/Light_Dark_Mode_Calculator/light.css
Js-Projects/Light_Dark_Mode_Calculator/main.html
Js-Projects/Light_Dark_Mode_Calculator/script.js

Calculator with Light and Dark Mode #1760 
Close #1760 
Fixed issue #1760 
Screen Recording of the project -
https://github.com/pranjay-poddar/Dev-Geeks/assets/70304320/99d6a286-574c-4dd1-9b84-22a94950ff12

Calculator with Light and Dark Mode

---

Js-Projects/Quiz-App/Readme.md
Js-Projects/Quiz-App/index.html
Js-Projects/Quiz-App/script.js
Js-Projects/Quiz-App/styles.css

Add a Quiz App in Js-Projects #1719
Close #1719
https://github.com/pranjay-poddar/Dev-Geeks/assets/105747510/1644eb3f-3e05-4b5b-9cb1-566d2bd701c5
https://github.com/pranjay-poddar/Dev-Geeks/assets/105747510/e496a28a-f4d8-45ed-ad9a-9634843ba02f

Added quiz game

---

Frontend-Projects/Durga-puja/.vscode/settings.json
Frontend-Projects/Durga-puja/index.html
Frontend-Projects/Durga-puja/style.css
Frontend-Projects/fruit_website/index.html
Frontend-Projects/fruit_website/styles.css

change navbar : Fruit website #1829

---

Frontend-Projects/Bus route booking system/README
Frontend-Projects/Bus route booking system/admin.html
Frontend-Projects/Bus route booking system/final.html
Frontend-Projects/Bus route booking system/index.html
Frontend-Projects/Bus route booking system/student.html
Frontend-Projects/Bus route booking system/student1.html
Frontend-Projects/Bus route booking system/viewreservationnew.html

Front- end Project: RouteEase [gssoc'23]
Please add the tag of gssoc'23.
Close #1703 
https://github.com/pranjay-poddar/Dev-Geeks/assets/111726483/8660e462-e2e7-4f8d-bb09-50d2879b0891

Adding a front-end project: RouteEase [gssoc'23]

---

Js-Projects/filter User App/README.md
Js-Projects/filter User App/index.html
Js-Projects/filter User App/index.js
Js-Projects/filter User App/style.css

Close #1032 
This is FilterUserApp , with the help of this we can fetch user information using filter functionality
And we can also add new User like Admin ,Developer , Designer ,Hr Manager etc.
[Screencast from 09-06-23 11:53:42 PM IST.webm](https://github.com/pranjay-poddar/Dev-Geeks/assets/90507983/9f8e83d9-8edf-4849-beb7-53d968fb097b)

added filterUser App

---

Repository_web_page/index.html
Repository_web_page/style.css

Updated the Footer section
#1664
Close #1664 
Before
After Updating

Add a creative Footer Scetion #1664 

---

index.html
style.css

Designing and Adding a proper footer with various links (Figma + JS) [GSSoC'23] #1806
Close #1806 
Before:
After:

Designed + Added the footer to the homepage

---

Js-Projects/Speed Typing Test/README.md
Js-Projects/Speed Typing Test/index.html
Js-Projects/Speed Typing Test/script.js
Js-Projects/Speed Typing Test/style.css

Typing Speed Test Website #1826 
Close #1826 
Screen Recording : 
https://github.com/pranjay-poddar/Dev-Geeks/assets/94905683/960f776b-8379-499a-ab65-137cd8116042

Added Typing Speed Test Website 

---

Navbars/animated_navbar/style.css

I have added z-index in css to correctly overlay the navbar.
Navbar is not correctly overlaying on webpage. #1974 
Close #1974

Fixed navbar not overlaying issue (#1)

---

Python Projects/VisualAnalysisApp/README.md
Python Projects/VisualAnalysisApp/analysis.py
Python Projects/VisualAnalysisApp/visualization.py

I have created a completely new project that will run and show the data analysis and visualization of a particular dataset.

data analysis & visualization app

---

Python Projects/Lizard-Spock-Game/Lizard_Spock_Game.ipynb
Python Projects/Lizard-Spock-Game/README.md

#1239 Lizard Spock Game
Close #1239

Lizard spock game

---

Java Projects/CALCULATOR/Calculator.java
Java Projects/CALCULATOR/README.md

Calculator in java projects #1227
Close #1227

Created calculator under GSSOC'23 #1227

---

README.md

Reverts pranjay-poddar/Dev-Geeks#1403

Revert "Readme.md Updated"

---

Js-Games/Snake Game/script.js
Js-Games/Snake Game/style.css
Js-Games/Snake_Game/index.html
Js-Games/Snake_Game/script.js
Js-Games/Snake_Game/style.css

To add a Snake Game #1903 
Close #1903
**Video**
https://github.com/pranjay-poddar/Dev-Geeks/assets/124715224/c674db09-241d-4bd4-b6d0-64600e206fb8

Adding Snake Game

---

Frontend-Projects/Restaurant site/CSS/style.css
Frontend-Projects/Restaurant site/about.html
Frontend-Projects/Restaurant site/contact.html
Frontend-Projects/Restaurant site/homepage.html
Frontend-Projects/Restaurant site/menu.html

Aboutus Page

---

MineSweeper game/Minesweeper.html
README.md

New Game MineSweeper added  #1027
Close #1027

New Game MineSweeper added 

---

Python Projects/stopwatch.py

The working principle of a stopwatch involves tracking the elapsed time between the start and stop events. When the stopwatch is started, it records the current time as the start time. As time progresses, it continually updates the elapsed time by subtracting the start time from the current time. When the stopwatch is stopped, it captures the end time and calculates the total elapsed time by subtracting the start time from the end time. This elapsed time is then displayed or used for further calculations. In more advanced stopwatches, additional functionalities like pausing and resuming the timer may be included. Pausing allows the user to temporarily suspend the stopwatch without losing the elapsed time, while resuming restarts the timer from the paused state. When a stopwatch is …

Stopwatch using python

---

Python Projects/Rockpaperscissors/READme
Python Projects/Rockpaperscissors/main.py

#Adding Rockpaperscissors game #1185
This pull request adds the Rock-Paper-Scissors game to the repository. The game allows users to play the classic hand game against the computer. It provides a fun and interactive experience for users to test their luck and strategic thinking.
This issue number is #1537 
Please review and merge this pull request to include the Rock-Paper-Scissors game in the repository.
Close #1185

Adding RockPaperScissors game

---

Python Projects/Tkinter Apps/A_way_to_hang_pc.py
Python Projects/Tkinter Apps/Clock_tk.py
Python Projects/Tkinter Apps/Image_Viewer.py
Python Projects/Tkinter Apps/README.md
Python Projects/Tkinter Apps/Stock_apple_current_data.py
Python Projects/Tkinter Apps/air_quality.py
Python Projects/Tkinter Apps/calculator_1.py
Python Projects/Tkinter Apps/google_search.py
Python Projects/Tkinter Apps/imdb_movie_data.py
Python Projects/Tkinter Apps/imdb_movie_search.py
Python Projects/Tkinter Apps/stock_market.py
Python Projects/Tkinter Apps/weather.py

Adding projects related to GUI creation using Tkinter, a Python library
Issue No #1044 
Close #1044

ADD : Python Apps made using Tkinter

---

Python Projects/password-generator/main.py

Add new project-password generator using python #1172
Close #1172

add a new project-password generator using python

---

Frontend-Projects/PathFindingVisualizer/README.md
Frontend-Projects/PathFindingVisualizer/index.html
Frontend-Projects/PathFindingVisualizer/pathfinding.js
Frontend-Projects/PathFindingVisualizer/styles.css

#Path Finding Visualizer  #2027 
Close #2027

PathFindingVisualizer

---

Frontend-Projects/AmazonClone/index.html
Frontend-Projects/AmazonClone/readme.md
Frontend-Projects/AmazonClone/script.js
Frontend-Projects/AmazonClone/style.css
README.md

Amazon clone #1645

---

ML Projects/AI-Virtual-Mouse-and-Keyboard-main/HandTracking.py
ML Projects/AI-Virtual-Mouse-and-Keyboard-main/README.md
ML Projects/AI-Virtual-Mouse-and-Keyboard-main/handTracker.py
ML Projects/AI-Virtual-Mouse-and-Keyboard-main/virttualmouse.py
ML Projects/AI-Virtual-Mouse-and-Keyboard-main/virtualkeybaord.py

Virtual Mouse and Keyboard is a Machine Learning based project.
Virtual Mouse and Keyboard #1464
Close #1464
Screen Recording:
https://github.com/pranjay-poddar/Dev-Geeks/assets/113499701/ff0d7cd1-1d44-47e3-a323-9c3e95e26c8a

Added Virtual Mouse and Keyboard Project

---

Frontend-Projects/N Queens Visualizer/README.md
Frontend-Projects/N Queens Visualizer/index.html
Frontend-Projects/N Queens Visualizer/n-queens.js
Frontend-Projects/N Queens Visualizer/style.css

The N Queens puzzle is the problem of placing N queens on an N x N chessboard such the no 2 queens attack each other i.e no two queens share the same row, column or diagonal. The above project demonstrates the process of finding all such possible configurations using the Backtracking Approach.
Close #1920 
https://github.com/pranjay-poddar/Dev-Geeks/assets/113793606/304cd2d5-8da4-4441-a477-8d55b03151df

N Queens Visualizer (FrontEnd Project)

---

Frontend-Projects/loanCalculator/README.md
Frontend-Projects/loanCalculator/index.html
Frontend-Projects/loanCalculator/index.js
Frontend-Projects/loanCalculator/style.css

Close #2007 
Screen Recording:
https://github.com/pranjay-poddar/Dev-Geeks/assets/117727361/79d2c740-4758-4474-94cc-08768bbfb472

Added loan calculator

---

Frontend-Projects/Realtime Character Counter/README.md
Frontend-Projects/Realtime Character Counter/index.html
Frontend-Projects/Realtime Character Counter/index.js
Frontend-Projects/Realtime Character Counter/style.css

Real Time Character Counter #2048
Close #2048 
https://github.com/pranjay-poddar/Dev-Geeks/assets/133862694/f27a6fe2-d93e-497e-bef1-e432fc1276a8

Realtime Character Counter

---

Frontend-Projects/Gym website/index.html

Issue number #1979 
1.Form is enhanced.
2.Background image is changed 
3.Enhancement in navigation bar
Close #1979

fixes some features in form, navbar and background.

---

Frontend-Projects/Shopclues.in/INDEXX.html
Frontend-Projects/Shopclues.in/Readme.md
Frontend-Projects/Shopclues.in/about.html
Frontend-Projects/Shopclues.in/blog.html
Frontend-Projects/Shopclues.in/cart.html
Frontend-Projects/Shopclues.in/contact.html
Frontend-Projects/Shopclues.in/script.js
Frontend-Projects/Shopclues.in/shop.html
Frontend-Projects/Shopclues.in/sproduct.html
Frontend-Projects/Shopclues.in/sproduct2.html
Frontend-Projects/Shopclues.in/style.css
INDEXX.html
Readme
about.html
blog.html
cart.html
contact.html
index.html
script.js
shop.html
sproduct.html
sproduct2.html
style.css

Title : Shopclues.in
Issue : #1935 
Close #1935
Recording of project : https://drive.google.com/file/d/1KwT31ryxpbtdLkYQEiCQq3NCG8Ygg35H/view?usp=drive_web

Shopclues.in

---

Frontend-Projects/Motivational code generator/Readme.md
Frontend-Projects/Motivational code generator/index.html
Frontend-Projects/Motivational code generator/motivate.json
Frontend-Projects/Motivational code generator/script.js
Frontend-Projects/Motivational code generator/style.css
INDEXX.html
Readme
about.html
blog.html
cart.html
contact.html
index.html
script.js
shop.html
sproduct.html
sproduct2.html
style.css

Title:Motivational code generator
Issue no:#2015
Close #2015
Video of project : https://prachisingh1008.github.io/Motivational-code-extension/

Motivational code generator

---

Frontend-Projects/BTech Tea Shop/css/style.css

Improving hamburger functionality: BTech Tea Shop #2008

---

Frontend-Projects/Responsive omnifood project/index.html

Menu items in Responsive Omnifood Project are not responding. [GSSoC'23] #1888
Close #1888 

Fixed menu items

---

Frontend-Projects/Day Planner/README.md
Frontend-Projects/Day Planner/index.html
Frontend-Projects/Day Planner/javascript.js
Frontend-Projects/Day Planner/style.css

It is the website that allows users to plan and organize their activities for a given day. The website will have a form where users can input their tasks or activities along with their corresponding time slots.
Day Planner  and the issue no is #1930
Close #1930

Day Planner

---

Python Projects/WeatherApp/WeatherApp.py

I Created a GUI Weather App in Python. It uses Open Weather Map API to fetch the latest weather information of cities and places around the globe.
Close #1235

WeatherApp Added

---

Js-Games/ColorMatcher/README.md
Js-Games/ColorMatcher/index.html
Js-Games/ColorMatcher/script.js
Js-Games/ColorMatcher/style.css

ColorMatcher #2113 
Close #2113

Adding ColorMatcher Game

---

Footers/content-footer/index.html
Footers/content-footer/style.css

Added the  CSS in content-footer and updated the html file also
Added the  CSS in content-footer and updated the html file and the issue no is #1799
Close #1799

Content-Footer

---

Js-Games/mathgame/README.md
Js-Games/mathgame/index.html
Js-Games/mathgame/script.js
Js-Games/mathgame/style.css

Adding mathgame

---

Js-Projects/Expanding Image Carousel/ReadMe.md
Js-Projects/Expanding Image Carousel/index.html
Js-Projects/Expanding Image Carousel/script.js
Js-Projects/Expanding Image Carousel/style.css

Expanding Image Carousel Project Addition.  Issue Number : #1257
Close #1257

Added my project Expanding Image Carousel  : for issue #1257

---

Js-Projects/Rotating-Image-Gallery/index.html
Js-Projects/Rotating-Image-Gallery/index.js
Js-Projects/Rotating-Image-Gallery/style.css

Rotating Image Carousel #2069
Close #2069 
https://github.com/pranjay-poddar/Dev-Geeks/assets/133862694/52f8e3b8-fb72-486f-ad9a-da69772cbf57

Rotating Image Gallery

---

Python Projects/Warning bot/warning_bot.py

Added warning bot

---

Js-Projects/Real time character counter/README.md
Js-Projects/Real time character counter/index.html
Js-Projects/Real time character counter/script.js
Js-Projects/Real time character counter/style.css

Issue Number:1000
Title - Real-time character counter
Tech used - HTML, CSS, and JS
closes #1000 
Checklist:
[x] I have mentioned the issue number in my Pull Request.
[x] I have commented on my code, particularly in hard-to-understand areas
[x] I have created a helpful and easy-to-understand README.md
[x] I have added the video link in the README.md file.
Video link: https://drive.google.com/file/d/1TVGmVujuyZDrydQvFqJPD73NN44eN-6m/view?usp=sharing

Adding Real time character counter project

---

Frontend-Projects/Animated Card/animated_card.css
Frontend-Projects/Animated Card/animated_card.html

Created an interactive and visually appealing card design using HTML and CSS.
Animated Card and the issue no is #1929
Close #1929

Animated Card

---

Js-Projects/2048game/2048.css
Js-Projects/2048game/2048.js
Js-Projects/2048game/Readme.md
Js-Projects/2048game/index.html

Adding 2048 game using javascript #2107 
Close #2107

Adding 2048 game using javascript

---

Js-Games/Whack_A_Mole_Game/README.md
Js-Games/Whack_A_Mole_Game/index.html
Js-Games/Whack_A_Mole_Game/mole.css
Js-Games/Whack_A_Mole_Game/mole.js

Close #2119 
The Whack-a-Mole game is a classic arcade game implemented using HTML, CSS, and JavaScript. Players must whack or hit moles that randomly pop up from holes on the screen. The game features a simple and intuitive user interface with responsive design elements.
- Hit moles that randomly pop up from holes on the screen
- Score points for successfully hitting moles
- Track your score as you play
- Responsive design for easy play on different devices
- Plants also pop up and if you click them then game is over

Added Whack a Mole Game

---

Frontend-Projects/event-keycodes/README.md
Frontend-Projects/event-keycodes/src/app.js
Frontend-Projects/event-keycodes/src/index.html
Frontend-Projects/event-keycodes/src/style.css

Added a new front-end project

---

Frontend-Projects/Bike E-commerce/index.html
Frontend-Projects/Bike E-commerce/style.css

Close #1361
-  [X] I have mentioned the issue number in my Pull Request.
-  [X] I have commented my code, particularly in hard-to-understand areas
-  [X] I have created a helpful and easy to understand `README.md`

This commit is made by Sahil Tyagi

---

Js-Games/jumble-word/index.html
Js-Games/jumble-word/script.js
Js-Games/jumble-word/styles.css

added new game #1395

---

Repository_web_page/index.html
Repository_web_page/script.js
Repository_web_page/style.css

Added a Scroll to top button on the website 
Close #2116

[ADD] Scroll to top button

---

Node-JS Projects/EJS-Blog-Challenge/app.js
Node-JS Projects/EJS-Blog-Challenge/package-lock.json
Node-JS Projects/EJS-Blog-Challenge/package.json
Node-JS Projects/EJS-Blog-Challenge/public/css/styles.css
Node-JS Projects/EJS-Blog-Challenge/views/about.ejs
Node-JS Projects/EJS-Blog-Challenge/views/compose.ejs
Node-JS Projects/EJS-Blog-Challenge/views/contact.ejs
Node-JS Projects/EJS-Blog-Challenge/views/home.ejs
Node-JS Projects/EJS-Blog-Challenge/views/partials/footer.ejs
Node-JS Projects/EJS-Blog-Challenge/views/partials/header.ejs
Node-JS Projects/EJS-Blog-Challenge/views/post.ejs

#1344 Add a NodeJS Full Stack App - Blogging Platform [GSSOC'23]
Close #1344

feat: Add Full Stack NodeJS Application

---

Animations-CSS/Pac_Man/index.html
Animations-CSS/Pac_Man/styles.css

Animated Pac-Man Using CSS successfully added for Issue #1065 
Close #1065 

Added Pac-Man CSS Animation

---

Frontend-Projects/BTech Tea Shop/README.md

#2036 Adding REAME file
Close #2036 

Added README file to Btech Tea Shop Site

---

Frontend-Projects/Bike E-commerce/README.md

README file has added to Bike E-commerce site

---

Frontend-Projects/Gym website/index.html
Frontend-Projects/Gym website/style.css

#1982 Improve about section 
Close #1982

redesign website

---

Animations-JS/HoverBoard Effect/index.html
Animations-JS/HoverBoard Effect/script.js
Animations-JS/HoverBoard Effect/style.css

HoverBoard Effect Added

---

Frontend-Projects/Apparel_Coming_Soon_Page/LICENSE
Frontend-Projects/Apparel_Coming_Soon_Page/README.md
Frontend-Projects/Apparel_Coming_Soon_Page/assets/css/styles.css
Frontend-Projects/Apparel_Coming_Soon_Page/assets/js/script.js
Frontend-Projects/Apparel_Coming_Soon_Page/index.html

[ADD]: APPAREL COMING SOON PAGE ✨

---

Frontend-Projects/Interactive_Rating_Component/LICENSE
Frontend-Projects/Interactive_Rating_Component/README.md
Frontend-Projects/Interactive_Rating_Component/index.html
Frontend-Projects/Interactive_Rating_Component/styles.css

[ADD]: INTERACTIVE RATING COMPONENT ✨

---

Frontend-Projects/pizza corner/index.html
Frontend-Projects/pizza corner/style.css

Created footer for the pizza corner website

---

Repository_web_page/index.html

align Intro div and image

---

Js-Games/ChessGrand/README.md
Js-Games/ChessGrand/index.html
Js-Games/ChessGrand/script.js
Js-Games/ChessGrand/style.css
README.md

[GSSoC'23] Add a Chess Game
Title: ChessGrand
Issue number: 2075
Close #2075

Added Chess game

---

Frontend-Projects/learning_webpage/css/style.css

This PR contains the updated code of the frontend project's "Learning_Webpage" homepage background fitting correction. This PR is the result of the following issue:
Frontend Project's "Learning_Webpage" Homepage Background Image Fitting Issues #1708
Close #1708

Frontend Project's "Learning_Webpage" Homepage Background Image Fitting Correction

---

Repository_web_page/index.html
Repository_web_page/style.css

close #2158 
Hi @pranjay-poddar, I've Improved the contrast and add a smooth scroll effect, please check

Improve contrast and scroll effect

---

Frontend-Projects/Password Validator/Passowrd.html
Frontend-Projects/Password Validator/Password.css
Frontend-Projects/Password Validator/Password.js

Changed the UI of password validator project (#1014)

---

Frontend-Projects/birthday website/gift.html
Frontend-Projects/game-survey form/game.html
Frontend-Projects/game-survey form/pong.html
Frontend-Projects/game-survey form/snake.html

Want to add some games on the website #1238
Close #1238

Added the games

---

.vscode/settings.json
Frontend-Projects/Advice_Generator/index.html
Frontend-Projects/Advice_Generator/index.js
Frontend-Projects/Advice_Generator/style.css

Random Advice App #2097
Close #2097 
https://github.com/pranjay-poddar/Dev-Geeks/assets/133862694/8cfb03cd-b798-4f63-96f9-ffac59fa615c

Added Advice Generator

---

Animations-CSS/Newtons-Bulb-Animation/index.html
Animations-CSS/Newtons-Bulb-Animation/style.css

- #2450 
Close #2450
https://github.com/pranjay-poddar/Dev-Geeks/assets/112793075/60a13634-55c0-4dc0-ac6a-51424040fefa

[GSSoC'23] :  Added Newton's Bulb Animation

---

Frontend-Projects/digital-clock/README.md
Frontend-Projects/digital-clock/index.html
Frontend-Projects/digital-clock/index.js
Frontend-Projects/digital-clock/style.css

Close #2152 
Screen Recording:
https://github.com/pranjay-poddar/Dev-Geeks/assets/117727361/9787573d-e2bf-4859-9537-a08e8d681669

added digital clock

---

Frontend-Projects/loancalci/Readme.md
Frontend-Projects/loancalci/index.html
Frontend-Projects/loancalci/script.js
Frontend-Projects/loancalci/style.css

Loan calculator
#1016 
Close #1016 <issue_no>

Loan Calculator

---

Animations-CSS/loader-animation/Readme.md
Animations-CSS/loader-animation/index.html
Animations-CSS/loader-animation/styles.css

CSS Loading Animation

---

README.md

Title: Tic Tac Toe.py link wrong in README.md
Issue Number: #2317
Close #2317 
Fixed the link of Tic Tac Toe.py in README.md

Fixed the link of Tic Tac Toe.py in README.md

---

Frontend-Projects/claymorphism-profile-card/index.html
Frontend-Projects/claymorphism-profile-card/style.css

#1496 CLAYMORPHISM PROFILE CARD
Close #1496 
HI @pranjay-poddar i have updated claymorphism profile card.
here is the screenshort of the final user interface design.
i hope you liked it
thank you for choosing me for this request.

updated claymorphism-profile-card

---

Frontend-Projects/disney hotstar clone/signin.html
Frontend-Projects/disney hotstar clone/signup.html
Frontend-Projects/disney hotstar clone/styles.css

I have created the signIn and signup page for the Disney Hotstar clone.
Please check and kindly inform me if you wanna any other changes.
Close #1092

SignIn and SignUp page added for the disney hotstar clone

---

Footers/Rfooter/css/style.css
Footers/Rfooter/index.html

Issue Title: Responsive Footer Design
Issue Number: #1109
Close #1109
The footer includes various sections such as company information, help, online shop, follow us, and a site map. The footer is 
styled using CSS to have a dark background color, white text, and hover effects for links and social media icons.
- Tested the footer on various screen sizes and devices to ensure responsiveness.
- Verified the accessibility of the links using automated accessibility testing tools.
- Manually checked the hover effects and responsiveness on different browsers.
- Apart from these features, some additional features were also added such as.
- Added SiteMap Section For some Extra feature
Here are some video illustrations of the above-mentioned: …

Added a Rfooter with Some  Changes

---

Js-Games/Catch Me If You Can/index.html
Js-Games/Catch Me If You Can/script.js
Js-Games/Catch Me If You Can/style.css
Js-Games/Move the Ball/index.html
Js-Games/Move the Ball/script.js
Js-Games/Move the Ball/style.css

Want to add JS Games - Issue No. - 2001
Close #2001

Added JS Games Catch Me if You Can & Move the Ball - Issue No. - 2001

---

Js-Projects/Percentage Scored/index.html
Js-Projects/Percentage Scored/script.js
Js-Projects/Percentage Scored/style.css

Want to add JS Project - Percentage Scored Issue no. - #2271
Close #2271

Added JS Project - Percentage Scored Issue no. #2271

---

Animations-CSS/CSS - Style Animations/3DCube.html
Animations-CSS/CSS - Style Animations/Animation1.html
Animations-CSS/CSS - Style Animations/Animation2.html
Animations-CSS/CSS - Style Animations/Animations.html
Animations-CSS/CSS - Style Animations/Styles.css
Animations-CSS/CSS - Style Animations/style.css
Animations-CSS/CSS - Style Animations/style1.css
Animations-CSS/CSS - Style Animations/style2.css

Want to add Css - Style Animations Issue No #2272
Close #2272

Added CSS - Style Animations Issue No #2272

---

Frontend-Projects/Fitness centre Website/index.html

1.changes navbar and other layouts
This commit includes comprehensive updates to the entire main page. The changes involve revising the layout, refining the content.
Issue #1992 
Close #1992

Fixed the main page

---

Frontend-Projects/Fitness centre Website/membership.html

1.added colorful rainbow cards to the page.
This commit introduces vibrant rainbow-themed cards to the page layout. Each card displays a unique color gradient, creating an eye-catching visual element.
issue #1992 
Close #1992

fixes the UI of membership page

---

Frontend-Projects/Fitness centre Website/blog latest.html

1.enhance the navbar
1.improves the UI by using bootstrap components.
issue #1992 
Close #1992

Fixes website's blog page

---

Frontend-Projects/Fitness centre Website/assets/css/BMI.css

issue #1992 
Adjusts the background gradient that will complements the main page and improves the UI of the BMI calculator.
Close #1992

resolves CSS styling for BMI calculator section of the website

---

Frontend-Projects/Fitness centre Website/Contactus.html

This commit involves a redesign of the form's user interface, introducing a more intuitive layout and styling that aligns with the gym website.
Issue #1992 
Close #1992

Fixes the Any Query user interface

---

Js-Games/1024_Moves/README.md
Js-Games/1024_Moves/index.html
Js-Games/1024_Moves/lost.js

added 1024_Moves game using javascript #2115 
Close #2115

Added 1024_Moves Game using JavaScript

---

Js-Projects/KeyPress Detector/index.html
Js-Projects/KeyPress Detector/script.js
Js-Projects/KeyPress Detector/styles.css

- #2530 
Close #2530
https://github.com/pranjay-poddar/Dev-Geeks/assets/112793075/53b38dfc-8364-41ff-b1d6-82921a0f1c8c

Added Keypress Detector

---

Java Projects/BMI calculator/BMICalculator.java
Java Projects/BMI calculator/README.md

added BMI calculator using java Gui #2517 
Close #2517

added BMI calculator using java Gui

---

Frontend-Projects/Responsive Travel Website/about.html
Frontend-Projects/Responsive Travel Website/contact.html
Frontend-Projects/Responsive Travel Website/index.html
Frontend-Projects/Responsive Travel Website/news.html
Frontend-Projects/Responsive Travel Website/style.css

Added links and design all other pages namely about,news and contact.
Redesigned the home page and enhanced some components
Close #1150

Project : Responsive Travel website

---

Python Projects/News Reader/README.md
Python Projects/News Reader/main.py

Successfully resolved Issue #1485 
Closes #1485 
[NewsReader.webm](https://github.com/pranjay-poddar/Dev-Geeks/assets/76618190/08bb61a4-38f2-4bfd-9a8f-ece1eebdecf3)

Adding project

---

Frontend-Projects/Food ordering website/index.html

Improved the Content of hole website which make it more attractive and nice.
Improved the content of food ordering website and the issue no is #1526
Close #1526

Food Ordering Website

---

Frontend-Projects/CARZILLA/AboutUs.html
Frontend-Projects/CARZILLA/README
Frontend-Projects/CARZILLA/WALLPAPERS.html
Frontend-Projects/CARZILLA/alloys.html
Frontend-Projects/CARZILLA/class25.html
Frontend-Projects/CARZILLA/exhaust.html
Frontend-Projects/CARZILLA/headlamps.html
Frontend-Projects/CARZILLA/index.html

Front- end Project: CARZILLA [gssoc'23]
Please add the tag of gssoc'23.
Close #2013 
https://github.com/pranjay-poddar/Dev-Geeks/assets/111726483/7d7445fb-32a9-43ec-bb64-590bffd542d6
I created a PR before but I got review to change somethings in it, this is updated version of that PR #2053

Adding a front-end project: CARZILLA [gssoc'23] 

---

Frontend-Projects/Spotify Clone/script.js
Frontend-Projects/Spotify Clone/style.css

Making Spotify Clone more interactive #2331
I have added Hover effect in Spotify clone and an event listener (when we click on song the masterplayer starts and stops)
Earlier
https://github.com/pranjay-poddar/Dev-Geeks/assets/127978268/a3df6342-948e-499e-b03d-85445f6d267e
Now
https://github.com/pranjay-poddar/Dev-Geeks/assets/127978268/68f6c114-d7c6-4981-b78d-149cbaa1599a
Close #2331

Hover effect Added 

---

c_pojects/student.c

Student database

---

Frontend-Projects/LinkedIn Like Button/index.html
Frontend-Projects/LinkedIn Like Button/index.js
Frontend-Projects/LinkedIn Like Button/style.css

close #2572 
Hi @MohitGupta121 , I've created a clone of LinkedIn like button component.
please consider merging my pull request.

Add LinkedIn like button component

---

Frontend-Projects/Basket_Sign_Up/LICENSE
Frontend-Projects/Basket_Sign_Up/README.md
Frontend-Projects/Basket_Sign_Up/assets/css/styles.css
Frontend-Projects/Basket_Sign_Up/assets/js/script.js
Frontend-Projects/Basket_Sign_Up/index.html

[ADD]: BASKET SIGN UP FORM PROJECT 💡

---

Js-Projects/Save Text as File/Readme.md
Js-Projects/Save Text as File/index.html
Js-Projects/Save Text as File/script.js
Js-Projects/Save Text as File/style.css

Issue No-
#2540
Title: Save text as a file
Close #<#2540>

Save text as file

---

cpp-projects/Swastika/README.md
cpp-projects/Swastika/Swastika.cpp

Title - SWASTIKA
Issue Number - 2747
Close #2747

[GSSoC'23] SWASTIKA Project Ready

---

Frontend-Projects/3-Column_Preview_Card_Component/LICENSE
Frontend-Projects/3-Column_Preview_Card_Component/README.md
Frontend-Projects/3-Column_Preview_Card_Component/index.html
Frontend-Projects/3-Column_Preview_Card_Component/styles.css

[ADD]: 3-COLUMN PREVIEW COMPONENT WEBSITE ✨

---

Js-Projects/Time-Watcher/README.md
Js-Projects/Time-Watcher/index.html
Js-Projects/Time-Watcher/script.js
Js-Projects/Time-Watcher/style.css

Title - Time Watcher
Issue Number - 2748
Close #2748

[GSSoC'23] Time Watcher Project Completed

---

Frontend-Projects/Online-Dictionary-App/README.md
Frontend-Projects/Online-Dictionary-App/index.html
Frontend-Projects/Online-Dictionary-App/main.js

Dictionary web app is added with issue number 
Close #2410

Dictionary web app added #2410

---

Python Projects/Kaun-Banega-Crorepati/Readme.md
Python Projects/Kaun-Banega-Crorepati/main.py

Kaun Banega Crorepati using Python issue number #2407 
Close #2407 
@pranjay-poddar Kindly merge it and give your feedback.
Under GSSOC'23

Kaun banega crorepati using python #2407 

---

Animations-CSS/Candle-Flame/README.md
Animations-CSS/Candle-Flame/index.html
Animations-CSS/Candle-Flame/style.css

Title - Candle Flame
Issue Number - 2819
Close #2819

[GSSoC'23] Flame Fire Animated Project completed.

---

AI_ChatGPT/README.md
AI_ChatGPT/script.js

Close #2852 
Hello @TusharKesarwani @MohitGupta121 
Added a Chatbot using the bridge of frontend and the backend the API. This API fetch the data from the sever and show the response to the user.

Added AI-ChatGPT

---

Preloaders/Placeholder-Shimmer-effect/index.html
Preloaders/Placeholder-Shimmer-effect/style.css

Close #2792 
https://github.com/pranjay-poddar/Dev-Geeks/assets/112793075/906589f2-dae2-43f9-b127-24f279bc7552

Added Placeholder shimmer effect

---

Js-Projects/Most_Spoken_Populated_Countries_Bar_Visualization_JS_Project/README.md
Js-Projects/Most_Spoken_Populated_Countries_Bar_Visualization_JS_Project/data/countries_data.js
Js-Projects/Most_Spoken_Populated_Countries_Bar_Visualization_JS_Project/data/countries_data_old.js
Js-Projects/Most_Spoken_Populated_Countries_Bar_Visualization_JS_Project/index.html
Js-Projects/Most_Spoken_Populated_Countries_Bar_Visualization_JS_Project/scripts/main.js
Js-Projects/Most_Spoken_Populated_Countries_Bar_Visualization_JS_Project/styles.css

[ADD]: COUNTRIES DATA BAR VISUALIZATION JS PROJECT ✨

---

Js-Projects/Solor_System_Objects_Weight_Calculator/README.md
Js-Projects/Solor_System_Objects_Weight_Calculator/data/planetsData.js
Js-Projects/Solor_System_Objects_Weight_Calculator/index.html
Js-Projects/Solor_System_Objects_Weight_Calculator/scripts/main.js
Js-Projects/Solor_System_Objects_Weight_Calculator/styles.css

[ADD]: SOLAR SYSTEM'S OBJECTS WEIGHT CALCULATOR ✨

---

Frontend-Projects/Kaun-Banega-Crorepati/README.md
Frontend-Projects/Kaun-Banega-Crorepati/index.html
Frontend-Projects/Kaun-Banega-Crorepati/main.js
Frontend-Projects/Kaun-Banega-Crorepati/style.css

Kaun Banega Crorepati Web Added #2406 
Close #2406

Kaun Banega Crorepati web added #2406

---

Python Projects/Encrypt-Decrypt/README.md
Python Projects/Encrypt-Decrypt/main.py

Encrypt Decrypt Using Python Added #2861
Close #2861

Encrypt Decrypt Using Python Added #2861

---

Frontend-Projects/Signup_login_page/index.html
Frontend-Projects/Signup_login_page/signup.html
Frontend-Projects/Signup_login_page/styles.css

#2854  login page
Close #2854 

#2854 New login page

---

Frontend-Projects/Education website/about.html
Frontend-Projects/Education website/contact.html
Frontend-Projects/Education website/homepage2.html
Frontend-Projects/Education website/skills.html
Frontend-Projects/Education website/style1.css

Close #2513 
- [ ✅] I have mentioned the issue number in my Pull Request.
- [ ✅] I have commented my code, particularly in hard-to-understand areas

Re-structured Education website

---

Java Projects/To-Do-List/README.md
Java Projects/To-Do-List/TodoListApp.java

A simple to-do list application built with Java Swing.
close #2800

Simple to do list desktop app using java swing

---

Js-Projects/Giveaway/index.html
Js-Projects/Giveaway/index.js
Js-Projects/Giveaway/style.css

Giveaway Project under JS projects #2620
Closes #2620

giveaway-project-added

---

Navbars/ScrollNavbar/index.html
Navbars/ScrollNavbar/index.js
Navbars/ScrollNavbar/style.css

scroll-navbar-added #2794
Close  #2794

scroll-navbar-added

---

Python Projects/Python API scraper/API_scraper.py
Python Projects/Python API scraper/requirements.txt

Added api scraper

---

Python Projects/Github scraper/Github_scraper.py

Added Github_scraper.py

---

Python Projects/Job_scraper/Job_scraper.py

Added Job_scraper.py

---

Frontend-Projects/Hotstar clone/index.html
Frontend-Projects/Hotstar clone/index.js
Frontend-Projects/Hotstar clone/styles.css

#2851 Disney hotstar clone website
Close #2851 

#2851 Hotstar clone website

---

Js-Projects/Customizable_Portfolio/README.md
Js-Projects/Customizable_Portfolio/data/userData.js
Js-Projects/Customizable_Portfolio/index.html
Js-Projects/Customizable_Portfolio/scripts/main.js
Js-Projects/Customizable_Portfolio/styles.css

[ADD]: CUSTOMIZABLE PORTFOLIO JS PROJECT ✨

---

Js-Projects/Random Jokes Generator/index.html
Js-Projects/Random Jokes Generator/script.js
Js-Projects/Random Jokes Generator/style.css

Random Jokes Generator
Issue #2486
Close #2486

Added Random Jokes Generator [GSSOC'23]

---

Frontend-Projects/XO Game/style.css

Frontend Project "XO Game" Design Improvement

---

Js-Projects/Players_Leaderboard/README.md
Js-Projects/Players_Leaderboard/index.html
Js-Projects/Players_Leaderboard/scripts/main.js
Js-Projects/Players_Leaderboard/styles.css

[ADD]: DYNAMIC LEADERBOARD PROJECT  ✨

---

Frontend-Projects/Mahatma_Gandhi_Biography/README.md
Frontend-Projects/Mahatma_Gandhi_Biography/index.html
Frontend-Projects/Mahatma_Gandhi_Biography/style.css

Title - Mahatma Gandhi - Biography
Issue Number - 2902
Close #2902

[GSSoC'23] Mahatma Gandhi Biography Ready

---

Frontend-Projects/Food ordering website/css/styles.css
Frontend-Projects/Food ordering website/index.html

It was already been completed before assigning to me. So, I made change which increases user experience.
Close #2806 

Adding content to Food Ordering website

---

Js-Games/ATLAS/README.md
Js-Games/ATLAS/index.html
Js-Games/ATLAS/script.js
Js-Games/ATLAS/style.css
README.md

Title: ATLAS
Issue: #2793
Close #2793

[GSSoC'23] Added the game of ATLAS

---

Frontend-Projects/Education website/README.md

Documentation for Education website
Close #2913 
- [ ✅] I have mentioned the issue number in my Pull Request.
-  [ ✅] I have commented my code, particularly in hard-to-understand areas
- [ ✅] I have created a helpful and easy to understand `README.md`

Added README.md file

---

Js-Projects/ChatBot/README.md
Js-Projects/ChatBot/index.html
Js-Projects/ChatBot/index.js
Js-Projects/ChatBot/style.css

Title - ChatBOT
Issue Number - 2901
Close #2901

[GSSoC'23] ChatBOT Project Ready

---

Frontend-Projects/Rock paper scissors game/index.html
Frontend-Projects/Rock paper scissors game/script.js
Frontend-Projects/Rock paper scissors game/styles.css

#2991 Add rock paper scissors game
Close #2991 

#2991 New_game added

---

Js-Projects/Etch_A_Sketch/README.md
Js-Projects/Etch_A_Sketch/fonts-imported.css
Js-Projects/Etch_A_Sketch/index.html
Js-Projects/Etch_A_Sketch/script.js
Js-Projects/Etch_A_Sketch/styles.css

[ADD]: ETCH A SKETCH GAME 💡

---

Frontend-Projects/calc.py

Make simple calculator using Python

---

Frontend-Projects/Countdown-Timer/index.html
Frontend-Projects/Countdown-Timer/index.js
Frontend-Projects/Countdown-Timer/styles.css

Close #2996
I have added the Countdown timer. Can it be merged now?

Countdown timer added

---

Frontend-Projects/Task manager/index.html
Frontend-Projects/Task manager/script.js
Frontend-Projects/Task manager/styles.css

#3043 Add task manager website
Close #3043 

#3043 Task_manager added

---

Repository_web_page/index.html
Repository_web_page/new/index.html
Repository_web_page/new/style.css
Repository_web_page/script.js
Repository_web_page/style.css

- Added the Scroll To Top Button. 
- Fixed the footer not appearing in the main webpage. 
- Made all the links open in a new tab when clicked instead of opening in the same tab of the website itself. 
- For Issue #3004 
Close #3004

Added Scroll To Top Button & Some Fixes

---

Js-Projects/Large_Factorial_Calculator/README.md
Js-Projects/Large_Factorial_Calculator/index.html
Js-Projects/Large_Factorial_Calculator/script.js
Js-Projects/Large_Factorial_Calculator/style.css

Title - Large Factorial Calculator
Issue Number - 2995
Close #2995

[GSSoC'23] Large Factorial Calculator Project Completed

---

Frontend-Projects/Ludo_Clone/README.md
Frontend-Projects/Ludo_Clone/index.html
Frontend-Projects/Ludo_Clone/style.css

Title - Ludo Clone
Issue Number - 2997
Close #2997

[GSSoC'23[ Ludo Front-end Clone

---

Js-Projects/World_Clock/README.md
Js-Projects/World_Clock/index.html
Js-Projects/World_Clock/script.js
Js-Projects/World_Clock/style.css
Js-Projects/World_Clock/timezone.json

Title - World Clock
Issue Number - 2993
Close #2993

[GSSoC'23] World Clock Ready

---

Frontend-Projects/Khabib_Nurmagomedov_Profile_Card_Component/README.md
Frontend-Projects/Khabib_Nurmagomedov_Profile_Card_Component/assets/styles.css
Frontend-Projects/Khabib_Nurmagomedov_Profile_Card_Component/index.html

[ADD]: KHABIB PROFILE CARD COMPONENT ✨

---

Frontend-Projects/Social_Proof_Section/README.md
Frontend-Projects/Social_Proof_Section/index.html
Frontend-Projects/Social_Proof_Section/styles.css

[ADD]: SOCIAL PROOF SECTION PAGE ✨

---

Java Projects/Flappy Bird Game/FlappyBird.java

Flappy Bird Game
Issue #3022
Close #3022

Added Flappy Bird Game [GSSOC'23]

---

Frontend-Projects/smart wearbles website/index.html
Frontend-Projects/smart wearbles website/readme.md

headphones and wearables website using HTML, CSS and JS
Close #2816

headphones and smart wearables website

---

React-JS Projects/To Do List App/.gitignore
React-JS Projects/To Do List App/README.md
React-JS Projects/To Do List App/package-lock.json
React-JS Projects/To Do List App/package.json
React-JS Projects/To Do List App/public/index.html
React-JS Projects/To Do List App/public/manifest.json
React-JS Projects/To Do List App/public/robots.txt
React-JS Projects/To Do List App/src/App.css
React-JS Projects/To Do List App/src/App.js
React-JS Projects/To Do List App/src/index.js

ReactJs To Do List App
Issue #2998
Close #2998

Added ReactJs To Do List App [GSSOC'23]

---

Frontend-Projects/Library/README.MD
Frontend-Projects/Library/index.html
Frontend-Projects/Library/style.css

Basic frontend project library added #2940 
Close #2940 
@MohitGupta121 Merge it or give your feedback.

Basic frontend project library added #2940 

---

Js-Projects/Theme Clock/index.html
Js-Projects/Theme Clock/script.js
Js-Projects/Theme Clock/style.css
Js-Projects/Theme Clock/timezones.json

- #3087 
Close #3087 
[ThemeClock.webm](https://github.com/pranjay-poddar/Dev-Geeks/assets/112793075/803a128a-06e5-4dda-bd1b-703eeb103986)

GSSoC'23 : Added timezone

---

Frontend-Projects/Gallery/README.md
Frontend-Projects/Gallery/index.html
Frontend-Projects/Gallery/main.js
Frontend-Projects/Gallery/preview.html
Frontend-Projects/Gallery/style.css

Gallery Template Frontend Project #2941
Close #2941
@MohitGupta121 Kindly merge it or give your feedback.

Gallery Frontend Project added

---

Animations-JS/PageScroll/index.html
Animations-JS/PageScroll/script.js
Animations-JS/PageScroll/style.css

- #3092 
Close #3092 
[Page Scroll.webm](https://github.com/pranjay-poddar/Dev-Geeks/assets/112793075/5b23536d-81f7-4103-9496-68b827484817)

Added page scroll animation

---

Frontend-Projects/Animated_Car/README.md
Frontend-Projects/Animated_Car/index.html
Frontend-Projects/Animated_Car/script.js
Frontend-Projects/Animated_Car/style.css

Title - Animated Car
Issue Number - 3068
Close #3068

[GSSoC'23] Car Animation Project Completed

---

Js-Projects/Battery_Status_Tracker/README.md
Js-Projects/Battery_Status_Tracker/index.html
Js-Projects/Battery_Status_Tracker/script.js
Js-Projects/Battery_Status_Tracker/style.css

Title - Battery Status Tracker
Issue Number - 3069
Close #3069

[GSSoC'23] Battery Status Tracker Project

---

Frontend-Projects/Anime_Pics_Generator/README.md

Added Readme file to the anime site
Close #3031 

Documentation for Anime pics Generator

---

Js-Projects/Distance_Convertor/README.md
Js-Projects/Distance_Convertor/error.js
Js-Projects/Distance_Convertor/formula.js
Js-Projects/Distance_Convertor/index.html
Js-Projects/Distance_Convertor/script.js
Js-Projects/Distance_Convertor/style.css

Title - Distance Convertor
Issue Number - 3063
Close #3063

[GSSoC'23] Distance Convertor Project Ready

---

Frontend-Projects/Banking_Website/README.md

Documentation for Banking website
Close #3032 

Update README.md in Banking website

---

Frontend-Projects/Bus route booking system/README.md

Re-structured readme file
Close #3033 

Documentation for bus route booking site

---

Frontend-Projects/FlowCV Login Page/contact.html
Frontend-Projects/FlowCV Login Page/index.html
Frontend-Projects/FlowCV Login Page/script.js
Frontend-Projects/FlowCV Login Page/services.html
Frontend-Projects/FlowCV Login Page/style.css

Building FlowCV website

---

c_pojects/PalindromeString/Palindrome.c
c_pojects/PalindromeString/ReadME.md

Palindrome String detector

---

Frontend-Projects/Indian Flag/README.md
Frontend-Projects/Indian Flag/index.html
Frontend-Projects/Indian Flag/style.css

Indian Flag Frontend project with details #2942 
Close #2942 
@MohitGupta121 
Kindly merge it or give your feedback.

Indian Flag Frontend project

---

Python Projects/Tic Tac toe/Read Me

# Wrong Link for read me file fir tik tok.py #2317

---

Js-Projects/Calculator/JSCalc.css

Title:- Improve the UI of the calculator.
Issue number:- #1034

UI of the calculator has been improved by using CSS.

---

Python Projects/.py to .apk/main.py
Python Projects/Ai Calculator/AI Calculator.py

Handling division by zero:
In the existing code, when a division by zero occurs, it raises an exception. You can modify the exception handling to display a meaningful message to the user, such as "Error: Division by zero is not allowed."
Basic arithmetic operations:
In addition to mathematical evaluation, you can add support for basic arithmetic operations like addition, subtraction, multiplication, and division. Instead of relying solely on mathematical evaluation, you can create your own logic adapters to handle these operations. This will allow the calculator to respond to queries like "What is 5 + 3?" or "Calculate 10 * 2."
Additional functions:
You can expand the calculator's capabilities by adding support for various mathematical functions such as square root, exponentiation, …

modified AI Calculator.py

---

Frontend-Projects/Random Jokes Generator/Readme.md
Frontend-Projects/Random Jokes Generator/index.html
Frontend-Projects/Random Jokes Generator/script.js
Frontend-Projects/Random Jokes Generator/style.css

Random Jokes Generator

---

Frontend-Projects/Classroom_Schedular_Website/README.md
Frontend-Projects/Classroom_Schedular_Website/index.html
Frontend-Projects/Classroom_Schedular_Website/script.js
Frontend-Projects/Classroom_Schedular_Website/style.css

Title - ClassRoom Schedular Website
Issue Number - 3072
Close #3072

[GSSoC'23] ClassRoom Schedular Website completed

---

Frontend-Projects/FlowCV Login Page/README.md

Documentation for FlowCV website

---

Frontend-Projects/weather-app/style.css

Frontend Project 'weather-app' Design Improvement

---

cpp-projects/Digital_Clock/README.md
cpp-projects/Digital_Clock/index.cpp

Hey! Admin I had Completed My Work  dIgital clock by `cpp`

Adding DigiClock Website in Cpp 

---

Frontend-Projects/WebPage Project new/style.css

Frontend Project 'WebPage Project new' Navbar Design Improvement

---

Frontend-Projects/WebPage Project new/style.css

Frontend Project 'WebPage Project new' Content Alignment Enhancement

---

Frontend-Projects/Login & Sign-Up/index.html
Frontend-Projects/Login & Sign-Up/readme.md
Frontend-Projects/Login & Sign-Up/signUp.html

- Added input validation in signup form through javascript function call
- Added redirection to login page after signing up
- Added built-in input validations in both signup and login forms.
Close #1589

Adding more features to login and signup front end project 

---

Js-Games/Music_Studio_Game/README.md
Js-Games/Music_Studio_Game/app.js
Js-Games/Music_Studio_Game/index.html
Js-Games/Music_Studio_Game/style.css

Title - Music Studio Game
Issue Number - 3213
Close #3213

[GSSoC'23] Music Studio Game Completed

---

Frontend-Projects/Valient-Institute-Site-main/style.css

Frontend Project "Valient-Institute-Site-main" Project Button Design Improvement
Close #3278

Frontend Project Valient-Institute-Site-main Project Button Design Improvement

---

Frontend-Projects/Travel Website Template/style.css

Frontend Project 'Travel Website Template' Content Alignment Enhancement
Close #3277

Frontend Project 'Travel Website Template' Content Alignment Enhancement

---

Frontend-Projects/TRAVEL-SITE-Home/style.css

Frontend Project 'TRAVEL-SITE-Home' Button Design Improvement
Close #3276

Frontend Project 'TRAVEL-SITE-Home' Button Design Improvement

---

Frontend-Projects/Clock Website/project_clock.html

Clock Website
Issue #3226
Close #3226

Added Clock Website [GSSOC'23]

---

Footers/animated_footer/.vscode/settings.json
Footers/animated_footer/index.html
Footers/animated_footer/style.css

added footerui

---

Frontend-Projects/TinDog website/css/styles.css

TinDog Project SignUp Button Hover Effect 
Close #3354

TinDog Project SignUp Button Hover Effect 

---

Frontend-Projects/thought generator/style.css

thought generation Project Styling
Close #3355

thought generation Project Styling

---

c_projects/Perfect Number/ReadMe.md
c_projects/Perfect Number/perfect_number.c

Perfect numbers

---

Frontend-Projects/To Do LIst/styles.css

Frontend Project "To Do List" Border Color Enhancement 
Close #3318

Frontend Project "To Do List" Border Color Enhancement

---

Frontend-Projects/Valient-Institute-Site-main/style.css

Frontend Project "Valient-Institute-Site-main" Contact Form Button Alignment Correction
Close #3311

Frontend Project "Valient-Institute-Site-main" Contact Form Button Alignment Correction

---

Frontend-Projects/Valient-Institute-Site-main/index.html
Frontend-Projects/Valient-Institute-Site-main/style.css

Frontend Project "Valient-Institute-Site-main" Review Section Content Alignment
Close #3310

Frontend Project "Valient-Institute-Site-main" Review Section Content Alignment

---

Frontend-Projects/Coming Soon Webpage/index.html
Frontend-Projects/Coming Soon Webpage/script.js
Frontend-Projects/Coming Soon Webpage/styles.css

Added Coming Soon Webpage for Issue #3348 
It was made using HTML, CSS & little bit of Javascript!
Responsive to low resolution devices.
Close #3348

Added Coming Soon Webpage under Frontend Projects

---

Js-Projects/CI_Calculator/README.md
Js-Projects/CI_Calculator/index.html
Js-Projects/CI_Calculator/script.js
Js-Projects/CI_Calculator/style.css

Title - Compound Interest Calculator
Issue Number - 3259
Close #3259

[GSSoC'23] Compound Interest Calculator Project Completed

---

Animations-CSS/Contact-Us/index.html

added animated contact page

---

Java Projects/Doraemon_Animation/DoraemonAnimation.java
Java Projects/Doraemon_Animation/Readme.md

Doraemon animation

---

Js-Games/Bouncing-Balls/README.md
Js-Games/Bouncing-Balls/index.html
Js-Games/Bouncing-Balls/main.js
Js-Games/Bouncing-Balls/style.css

Title - Bouncing Balls
Issue Number - 3258
Close #3258

[GSSoC'23] Bouncing Balls Animation Ready

---

Js-Projects/Text-Analyzer/README.md
Js-Projects/Text-Analyzer/index.html
Js-Projects/Text-Analyzer/script.js
Js-Projects/Text-Analyzer/style.css

Title - Text Analyzer
Issue Number - 3262
Close #3262

[GSSoC'23] Text Analyzer Project Ready

---

Frontend-Projects/The coffee house/coffeehouse.css

Frontend Project "The coffee house" Homepage Button Design Enhancement
Close #3406

Frontend Project "The coffee house" Homepage Button Design Enhancement

---

Frontend-Projects/The coffee house/coffeehouse.css

Frontend Project "The coffee house" Homepage Alignment
Close #3407

Frontend Project "The coffee house" Homepage Alignment

---

Frontend-Projects/The coffee house/coffeehouse.css

Frontend Project "The coffee house" Menu Section's Buttons Design Improvement 
Close #3409

Frontend Project "The coffee house" Menu Section's Buttons Design Improvement 

---

Frontend-Projects/TBT/style.css

Frontend Project "TBT" Contact Form Design Improvement
Close #3412

Frontend Project "TBT" Contact Form Design Improvement

---

Animations-CSS/Waves_Animation/index.html
Animations-CSS/Waves_Animation/styles.css

Succesfully added the Wave Animation using CSS for Issue #3385 
Close #3385

Added Wave CSS Animation

---

Frontend-Projects/Events_landing_page/assets/css/custom.css
Frontend-Projects/Events_landing_page/index.html

Enhanced Event Landing Page

---

Frontend-Projects/AdventureAwaits/readme.md

Update readme.md file for Adventure awaits page

---

Frontend-Projects/CARZILLA/README

Update Readme file to Carzilla Site

---

Frontend-Projects/Social_Proof_Section/styles.css

Frontend Project "Social_Proof_Section" Styling
Close #3452
**Before**
**After**

Frontend Project "Social_Proof_Section" Styling

---

Frontend-Projects/Task manager/styles.css

Frontend Project "Task manager" 'Add task' Button Design
Close #3415
**Before**
**After**

Frontend Project "Task manager" 'Add task' Button Design

---

Frontend-Projects/Task manager/styles.css

Frontend Project "Task manager" Content Styling
Close #3414
**Before**
**After**

Frontend Project "Task manager" Content Styling

---

Frontend-Projects/Advice_Generator/README.md

Create README.md file for Advice Generator

---

Frontend-Projects/Starbucks Frontend/style.css

Frontend Project "Starbucks Frontend" Homepage Paragraph Improved Styling
Close #3451
**Before**
**After**

Frontend Project "Starbucks Frontend" Homepage Paragraph Improved Styling

---

Frontend-Projects/Sudoku Solver/sudokuSolver/style.css

Frontend Project "Sudoku Solver" Buttons Hover Effect Addition
Close #3450
**Before**
**After**

Frontend Project "Sudoku Solver" Buttons Hover Effect Addition

---

Frontend-Projects/Sudoku Solver/sudokuSolver/style.css

Frontend Project "Sudoku Solver" Buttons Styling
Close #3449
**Before**
**After**

Frontend Project "Sudoku Solver" Buttons Styling

---

Frontend-Projects/Task manager/styles.css

Frontend Project "Task manager" 'Edit and Delete' Buttons Design Enhancement
Close #3416
Before
After

Frontend Project "Task manager" 'Edit and Delete' Buttons Design Enhancement

---

Animations-CSS/Smoky Spiral Animation/index.html
Animations-CSS/Smoky Spiral Animation/styles.css

Successfully added Smoky Spiral Animation using CSS for Issue #3465 
Close #3465

Added Smoky Spiral CSS Animation

---

Frontend-Projects/Insta Clone/index.html
Frontend-Projects/Insta Clone/script.js
Frontend-Projects/Insta Clone/styles.css

Successfully added scroll to top button with a another script.js file for Issue #3493
Close #3493

Frontend Project "Insta Clone": Added Scroll To Top Button

---

Frontend-Projects/AdventureAwaits/css/styles.css
Frontend-Projects/AdventureAwaits/index.html

issue title: adding transition & animation to social media icons to adventure awaits - frontend project #3377
Close #3377

hover effect to social media icons

---

c_projects/Decimal to Binary/ReadMe.md
c_projects/Decimal to Binary/decimal_to_binary.c

decimal to binary converter

---

Frontend-Projects/Fully Responsive University Website/about.html
Frontend-Projects/Fully Responsive University Website/blog.html
Frontend-Projects/Fully Responsive University Website/contact.html
Frontend-Projects/Fully Responsive University Website/course.html
Frontend-Projects/Fully Responsive University Website/index.html
Frontend-Projects/Fully Responsive University Website/style.css

Fully Responsive University Website
Issue #2487
Close #2487

Added Fully Responsive University Website [GSSOC'23]

---

cpp-projects/ATM_banking/ATM.cpp

#3580 and ATM banking c++
Close #3580

ATM banking c++

---

cpp-projects/KBC game/kbc.cpp

#3579  and KBC game c++
Close #3579

KBC game c++

---

cpp-projects/Flight management/Flight.cpp

#3581 and flight management c++ project
Close #3581

flight management c++ project

---

Frontend-Projects/BeautifulTweets/index.html
Frontend-Projects/BeautifulTweets/style.css

added new tweets, edited previous tweets and added shadow to the tweet boxes
add new tweet to beautiful tweets - frontend project #3380
Close #3380

added new tweets

---

Frontend-Projects/Algo_Viewer/README.md

Documentation to Algo viewer site

---

Frontend-Projects/Community Page/community.html
Frontend-Projects/Community Page/index.html
Frontend-Projects/Community Page/register.html

Enhanced Community page

---

Animations-CSS/Lighthouse Animation/index.html
Animations-CSS/Lighthouse Animation/styles.css

Successfully added a CSS Animation of Lighthouse for Issue #3492 
Close #3492

Added Lighthouse CSS Animation

---

Frontend-Projects/Mahatma_Gandhi_Biography/index.html
Frontend-Projects/Mahatma_Gandhi_Biography/script.js
Frontend-Projects/Mahatma_Gandhi_Biography/style.css

Successfully added scroll to top button for the website for Issue #3495 
Close #3495

Frontend Projects: "Mahatma Gandhi Biography"   'Added Scroll To Top Button'

---

c_projects/Compound Interest/ReadMe.md
c_projects/Compound Interest/compoundInterest.c

compounded amount calculator

---

Animations-CSS/Animated Eyes/Readme.md
Animations-CSS/Animated Eyes/app.js
Animations-CSS/Animated Eyes/index.html
Animations-CSS/Animated Eyes/style.css

Animated eyes follow cursor

---

.github/workflows/prevent_multiple_issues.yml

<ul>
<li>@pranjay-poddar needs to enable <b>Read and Write Permissions</b> for this Github Bot.</li>
<li>Go to <b>Dev-Geeks</b> repository Settings</li>
<li>
<details>
<summary>Click to see the screenshot to make minor change</summary>
</details>
</li>
<li>This step is way more simpler than the old method of using <kbd>PERSONAL_ACCESS_TOKEN</kbd>.</li>
</ul>

chore: update workflow to use github bot ✨

---

Frontend-Projects/Sky Scapper game/style.css

Frontend Project "Sky Scapper game" Button 'Start' Improved Styling
Close #3454
**Before**
**After**

Frontend Project "Sky Scapper game" Button 'Start' Improved Styling

---

Frontend-Projects/Sample-Frontend-Project/style.css

Frontend Project "Sample-Frontend-Project" Homepage Content Alignment
Close #3470 
**Before**
**After**

Frontend Project "Sample-Frontend-Project" Homepage Content Alignment

---

Frontend-Projects/SIGN UP FORM/style.css

Frontend Project "SIGN UP FORM" Improved Styling
Close #3455
**Before**
**After**

Frontend Project "SIGN UP FORM" Improved Styling

---

Frontend-Projects/Sample-Frontend-Project/style.css

Frontend Project "Sample-Frontend-Project" 'What is CRAZYSTOCKS' Section Styling 
Close #3471 
**Before**
**After**

Frontend Project "Sample-Frontend-Project" 'What is CRAZYSTOCKS' Section Styling 

---

Frontend-Projects/Sample-Frontend-Project/style.css

Frontend Project "Sample-Frontend-Project" Login Form Styling
Close #3472
**Before**
**After**

Frontend Project "Sample-Frontend-Project" Login Form Styling

---

Frontend-Projects/Sample-Frontend-Project/style.css

Frontend Project "Sample-Frontend-Project" 'Check Out Our Specialized Services' Section Styling
Close #3473 
**Before**
**After**

Frontend Project "Sample-Frontend-Project" 'Check Out Our Specialized Services' Section Styling

---

Frontend-Projects/Sample-Frontend-Project/style.css

Frontend Project "Sample-Frontend-Project" 'Contact Us Now' Section Styling
Close #3475
**Before**
**After**

Frontend Project "Sample-Frontend-Project" 'Contact Us Now' Section Styling

---

Frontend-Projects/Sample-Frontend-Project/style.css

Frontend Project "Sample-Frontend-Project" 'Here’s what our users have to say' Section Styling
Close #3474
**Before**
**After**

Frontend Project "Sample-Frontend-Project" 'Here’s what our users have to say' Section Styling

---

Frontend-Projects/Random Color Generator/style.css

Frontend Project "Random Color Generator" Improved Design
Close #3544
**Before**
**After**

Frontend Project "Random Color Generator" Improved Design

---

Frontend-Projects/Random Quote generator/style.css

Frontend Project "Random Quote generator" Improved Styling
Close #3545 
**Before**
**After**

Frontend Project "Random Quote generator" Improved Styling

---

Frontend-Projects/Random-image-slider/index.html
Frontend-Projects/Random-image-slider/styles.css

Frontend Project "Random-image-slider" Improved Styling
Close #3546 
**Before**
**After**

Frontend Project "Random-image-slider" Improved Styling

---

Frontend-Projects/Recipe_Book/style.css

Frontend Project "Recipe_Book" Styling
Close #3547
**Before**
**After**

Frontend Project "Recipe_Book" Styling

---

Frontend-Projects/razorpayClone/index.html

Frontend Project "razorpayClone" 'Explore Razorpay Business Banking' Section Uneven Color Correction
Close #3550
**Before**
**After**

Frontend Project "razorpayClone" 'Explore Razorpay Business Banking' Section Uneven Color Correction

---

Frontend-Projects/registration form/index.html
Frontend-Projects/registration form/styles.css

Frontend Project "registration form" Updated Design
Close #3548 
**Before**
**After**

Frontend Project "registration form" Updated Design

---

Frontend-Projects/Realtime Character Counter/style.css

Frontend Project "Realtime Character Counter" Styling
Close #3551 
**Before**
**After**

Frontend Project "Realtime Character Counter" Styling

---

Frontend-Projects/smart wearbles website/index.html

Frontend Project "smart wearbles website" Content Styling 
Close #3453
**Before**
**After**

Frontend Project "smart wearbles website" Content Styling 

---

Frontend-Projects/Sample-Frontend-Project/style.css

Frontend Project "Sample-Frontend-Project" Navbar Improved Styling
Close #3469
**Before**
**After**

Frontend Project "Sample-Frontend-Project" Navbar Improved Styling

---

Frontend-Projects/Community Page/README.md

Created README file

---

Animations-CSS/Bubbles Animation/index.html
Animations-CSS/Bubbles Animation/styles.css

Successfully added a css animation of floating bubbles in background for Issue #3560 
Close #3560

Added Bubbles CSS Animation

---

Js-Games/GeoGuess/README.md
Js-Games/GeoGuess/game.html
Js-Games/GeoGuess/script.js
Js-Games/GeoGuess/style.css
README.md

Added the game geo-guess, along with it's necessary README and documentation. 
Close #3391

Added the Geo-guess javascript game

---

Js-Projects/Lorem-Ipsum-Generator/README.md
Js-Projects/Lorem-Ipsum-Generator/loremipsum-generator.html
Js-Projects/Lorem-Ipsum-Generator/script.js
Js-Projects/Lorem-Ipsum-Generator/style.css

Title - Lorem Ipsum Generator
Issue Number - 3570
Close #3570

[GSSoC'23] Lorem Ipsum Generator Project Completed

---

Animations-CSS/Neon-Light/README.md
Animations-CSS/Neon-Light/index.html
Animations-CSS/Neon-Light/style.css

Title - Neon Light Effect
Issue Number - 3573
Close #3573

[GSSoC'23] Neon Light Effect using CSS

---

Python Projects/National_Flag/README.md
Python Projects/National_Flag/flag-N.py

indian national flag

---

Python Projects/Election Management/Elections.py
Python Projects/Election Management/README.md

Election Management System #3618 
Close #3618 
Please review this PR  under GSSOC'23.

 Election Management System using Python-MySql  [GSSOC'23]

---

Frontend-Projects/Painting_Game/style.css

Frontend Project "Painting_Game" Improved Styling
Close #3631 
**Before**
**After**

Frontend Project "Painting_Game" Improved Styling

---

Frontend-Projects/Results_Summary_Component/styles.min.css

Frontend Project "Results_Summary_Component" Heading Alignment
Close #3630 
**Before**
**After**

Frontend Project "Results_Summary_Component" Heading Alignment

---

Frontend-Projects/Restaurant site/CSS/style.css
Frontend-Projects/Restaurant site/homepage.html

Frontend Project "Restaurant site" Homepage Design Improvement
Close #3629 
**Before**
**After**

Frontend Project "Restaurant site" Homepage Design Improvement

---

Python Projects/Web-Image Filter/webimagefilter.py

I've added the following filters in the project -
- Gaussian Blur
- Duo Tone
- Pencil Sketch
- Colored Sketch
- Cartoon(light)
- Cartoon(dark)
- Emboss
- Splash
- Canny
Close #3457

Added multiple filters in Web Image Filter project

---

Python Projects/CollegeGPACalculator/README.md
Python Projects/CollegeGPACalculator/collegegpacalculator.py
README.md

I've added the necessary project into the ```Python Projects``` folder. For this I've used the Tkinter library for setting up the required GUI for the calculator application. 
Close #3456

Added College CGPA calculator project

---

Js-Projects/Cryptopia/README.md
Js-Projects/Cryptopia/assets/ap.js
Js-Projects/Cryptopia/assets/script.js
Js-Projects/Cryptopia/assets/style.css
Js-Projects/Cryptopia/index.html

Web Development project: Cryptopia [gssoc23]
Previously, I opened a PR for the same issue, but i was asked to do some improvements so this is an updated PR. Previous PR #3013 
https://github.com/pranjay-poddar/Dev-Geeks/assets/111726483/26172041-086e-4b42-b21a-1b9afd9b0d49
Please add the tag of gssoc23

Adding a web development project: Cryptopia [gssoc23]

---

Frontend-Projects/Landing_Page_Template_Project/README.md
Frontend-Projects/Landing_Page_Template_Project/index.html
Frontend-Projects/Landing_Page_Template_Project/styles.css

ADD: LANDING PAGE TEMPLATE PROJECT ✨

---

Navbars/Sidebar/index.html
Navbars/Sidebar/index.js
Navbars/Sidebar/style.css

Add a Navbar with a sidebar under Navbar Projects #3236
Close #3236

navbar with a sidebar added

---

ML Projects/House Price prediction using Regression model/House_Price_Prediction.ipynb
ML Projects/House Price prediction using Regression model/readme.md

ML- House price prediction using Regression model (Gssoc'23) #1134
Close #1134

House price prediction

---

Js-Games/Maze/ReadMe.md
Js-Games/Maze/index.html
Js-Games/Maze/main.js

Added Simple Maze

---

Animations-JS/Connecting Particles/README.md
Animations-JS/Connecting Particles/index.html
Animations-JS/Connecting Particles/script.js
Animations-JS/Connecting Particles/styles.css

Successfully added a JS animation about particle background that connect with each other with a line for Issue #3758 
Close #3758

Added Connecting Particles JS Interactive Animation

---

Animations-JS/Colorful Interactive Particles/README.md
Animations-JS/Colorful Interactive Particles/index.html
Animations-JS/Colorful Interactive Particles/script.js
Animations-JS/Colorful Interactive Particles/styles.css

Successfully added a Javascript project animation of colorful interactive particles for Issue #3761 
Close #3761

Added Colorful Interactive Particles using Javascript

---

cpp-projects/Reportcard/studentcard.cpp

#3732 and student card
Close #3732

studentcard.cpp

---

Js-Projects/Random-Meal-Generator/README.md
Js-Projects/Random-Meal-Generator/index.html
Js-Projects/Random-Meal-Generator/script.js
Js-Projects/Random-Meal-Generator/style.css

Title - Random meal generator
Issue Number - 3574
Close #3574

[GSSoC'23] Random Meal Generator Project Ready

---

Js-Projects/Recipe-Finder-Website/README.md
Js-Projects/Recipe-Finder-Website/index.html
Js-Projects/Recipe-Finder-Website/script.js
Js-Projects/Recipe-Finder-Website/style.css

Title - Recipe Finder
Issue Number - 3575
Close #3575

[GSSoC'23] Recipe Finder Project Completed

---

Js-Projects/CGPA_Calculator/README.md
Js-Projects/CGPA_Calculator/index.html
Js-Projects/CGPA_Calculator/script.js
Js-Projects/CGPA_Calculator/style.css

CGPA calculator using JavaScript
Issue number: 3672
Close #3672

Added CGPA calculator (for js-projects)

---

Frontend-Projects/BTech Tea Shop/css/style.css
Frontend-Projects/BTech Tea Shop/index.html

 [B.Tech Tea Shop] Adding related content to Review section

---

Frontend-Projects/BTech Tea Shop/css/style.css
Frontend-Projects/BTech Tea Shop/index.html

[B.Tech Tea Shop] Enhancing content and components to Contact Section

---

Python Projects/Dictionary/READ_ME.md
Python Projects/Dictionary/dict.py

#3462 
Close #3462
##Description:
A dictionary project in Python with GUI that emulates a digital dictionary. It allows users to enter a word and retrieves its corresponding meaning from a preloaded dictionary database. It also has get_close_matches function to detect spelling errors and suggest the word closest to it.
Screenshots:

 Dictionary App in Python with GUI 

---

Frontend-Projects/BTech Tea Shop/css/style.css
Frontend-Projects/BTech Tea Shop/index.html

Blog Section styling [B.Tech Tea Shop]

---

Frontend-Projects/Chess Website/README.md
Frontend-Projects/Chess Website/index.html
Frontend-Projects/Chess Website/script.js
Frontend-Projects/Chess Website/style.css

[NEW PROJECT] Chess Website

---

Animations-CSS/Submarine Animation/README.md
Animations-CSS/Submarine Animation/index.html
Animations-CSS/Submarine Animation/style.css

**Submarine Animation**
Issue #3824 
Close #3824

Submarine Animation[GSSOC'23]

---

Python Projects/Book Scraper/README.md
Python Projects/Book Scraper/main.py
Python Projects/Book Scraper/requirements.txt

Close #3850 
[Screencast from 21-07-23 04:05:54 PM IST.webm](https://github.com/pranjay-poddar/Dev-Geeks/assets/85278243/e643b2fb-f3d7-4f45-8e6f-ef99394cafb8)

Added a Book Scraper

---

Animations-CSS/ImageTextReveal/index.html
Animations-CSS/ImageTextReveal/style.css

- #3679 
Close #3679 
https://github.com/pranjay-poddar/Dev-Geeks/assets/112793075/7cd4c7ee-d8bb-4867-b9cc-473b73a9a244

Added Image Text Reveal Animation

---

c_projects/Movie Management System/Movie.c
c_projects/Movie Management System/README.md

Movie Ticketing System 
Issue number #3892
Close #3892 
@MohitGupta121 sir kindly review and merge this PR

Movie Ticketing System #3892

---

Repository_web_page/index.html
Repository_web_page/new/style.css

revamp: dev-geeks footer style ✨

---

Frontend-Projects/Cofee shop website/index.html
Frontend-Projects/Cofee shop website/style.css

Issue: making navbar interactive- coffee shop website- frontend project #3814
Close #3814

navbar updation

---

Frontend-Projects/onlineclothshopping website/style.css

'We know you breathe fashion' Section's Heading Correction
Close #3720
**Before**
**After**

'We know you breathe fashion' section correction

---

Js-Projects/FileReader/index.html
Js-Projects/FileReader/script.js
Js-Projects/FileReader/style.css

- #3680 
Close #3680
https://github.com/pranjay-poddar/Dev-Geeks/assets/112793075/cd3afa75-aa89-4a40-b70b-e7f02cddee92

Added file reader

---

c_projects/Matrix Calculator/ReadMe.md
c_projects/Matrix Calculator/matrix_calculator.c

matrix calculator

---

Animations-CSS/Order-Complete-Button/index.html
Animations-CSS/Order-Complete-Button/script.js
Animations-CSS/Order-Complete-Button/style.css

I have added a button with order complete animation using JS and CSS
Close #3852

Added a Order Complete Button

---

Python Projects/Bus booking management System/README.md
Python Projects/Bus booking management System/main.py

Bus management system using python.
You can create new buses, book tickets, view tickets, and see the summary
Close #3910 
https://github.com/pranjay-poddar/Dev-Geeks/assets/111726483/2bfa6929-4258-4ddf-9ede-e6e2d45a6823

[Add a new project] Bus booking management System using python [gssoc23]

---

Animations-CSS/Interactive Cards/README.md
Animations-CSS/Interactive Cards/index.html
Animations-CSS/Interactive Cards/script.js
Animations-CSS/Interactive Cards/styles.css

Successfully added a css/js animation project involving 5 interactive cards each having a beautiful scenery of nature accompanied with a nature related quote.
https://github.com/pranjay-poddar/Dev-Geeks/assets/83227649/8070ec30-4de6-47ac-90b8-c3b0b362b610
Close #4002

Added Interactive Cards CSS/JS Animation

---

Frontend-Projects/Parking Lot Management System/Readme.md

Create Readme.md for Parking Site

---

Animations-CSS/Clock Animation/ReadMe.md
Animations-CSS/Clock Animation/index.html
Animations-CSS/Clock Animation/style.css

clock animation

---

Animations-CSS/Rotating Words/ReadMe.md
Animations-CSS/Rotating Words/index.html
Animations-CSS/Rotating Words/style.css

Css animation: rolling words

---

c_projects/Library management system/library.c

Library management in C

---

Animations-CSS/Basketball Animation/README.md
Animations-CSS/Basketball Animation/index.html
Animations-CSS/Basketball Animation/style.css

**Basketball Animation**
**Issue** #4034  
Close #4034

Basketball Animation[GSSOC'23]

---

Footers/goofy footer/index.html

goofy footer added

---

Js-Games/Ludo Game/Ludo-game.html
Js-Games/Ludo Game/Ludo-game.js

Ludo Game
Issue #3914
Close #3914

Added Ludo Game [GSSOC'23]

---

Animations-CSS/CASSETTE Animation/README.md
Animations-CSS/CASSETTE Animation/index.html
Animations-CSS/CASSETTE Animation/style.css

**CASSETTE Animation**
Issue #4035 
Close #4035

CASSETTE Animation[GSSOC'23]

---

Frontend-Projects/Image-Gallery-Generator/index.html
Frontend-Projects/Image-Gallery-Generator/script.js
Frontend-Projects/Image-Gallery-Generator/style.css

Image-gallery-generator

---

Js-Projects/weight converter/weight.html

weight converter added

---

Frontend-Projects/pet website/index.html
Frontend-Projects/pet website/style.css

pet website added

---

c_projects/Tower of Hanoi/ReadMe.md
c_projects/Tower of Hanoi/Tower_of_Hanoi.c

C_project: Tower of Hanoi

---

Frontend-Projects/footer-template/index.html
Frontend-Projects/footer-template/styles.css

#4105 
Creative Footer template
Close #4105

#4105 Footer template added

---

Java Projects/Contact Book/ContactBook.java
Java Projects/Contact Book/README.md

Implement Contact Book Management System In java language
Issue Number #3942
Close these issue #3942

Implement Contact Book Management System #3942

---

Repository_web_page/Darkthem.css
Repository_web_page/Darktheme.js
Repository_web_page/index.html

I added a toggle button which switches the theme of Repository webpage of Dev-geeks, from light theme to dark theme, and then dark theme to light theme.  
Close #3768 
https://github.com/pranjay-poddar/Dev-Geeks/assets/111726483/9d879367-0880-40f4-a247-945dfede8e6e

Added Dark theme option to the repository webpage of Dev-geeks. [gssoc23]

---

Frontend-Projects/olx/style.css

Frontend Project "olx" 'Categories' Section Boxes Design
Close #3715 
**Before**
**After**

'Categories' Section Boxes Design

---

Frontend-Projects/NFTCardComponent/styles.css

Frontend Project "NFTCardComponent" Content Alignment
Close #3713
**Before**
**After**

Frontend Project "NFTCardComponent" Design Enhancement

---

Frontend-Projects/numbertowords/style.css

rontend Project "numbertowords" Styling
Close #3714 
**Before**
**After**

Frontend Project "numbertowords" Styling

---

Java Projects/Hangman Game/Hangman.java
Java Projects/Hangman Game/README.md

The Hangman Game is a command-line word guessing game written in Java language.
Issue number #4017 
Close #4017 
@MohitGupta121 @pranjay-poddar Sir kindly review the project

Hangman Game in JAVA

---

Java Projects/TypingSpeedTest/ApplicationMode.java
Java Projects/TypingSpeedTest/ITextRepository.java
Java Projects/TypingSpeedTest/LeaderLevel.java
Java Projects/TypingSpeedTest/QueuedEditEvent.java
Java Projects/TypingSpeedTest/QueuedInsert.java
Java Projects/TypingSpeedTest/QueuedRemove.java
Java Projects/TypingSpeedTest/README.md
Java Projects/TypingSpeedTest/TextSampleRepository.java
Java Projects/TypingSpeedTest/TimeCounter.java
Java Projects/TypingSpeedTest/TypingTestController.java
Java Projects/TypingSpeedTest/TypingTestView.form
Java Projects/TypingSpeedTest/TypingTestView.java
Java Projects/TypingSpeedTest/i18n/I18nHelper.java
Java Projects/TypingSpeedTest/recognizer/CompareHelper.java
Java Projects/TypingSpeedTest/recognizer/TextChain.java
Java Projects/TypingSpeedTest/recognizer/TextEntry.java
Java Projects/TypingSpeedTest/recognizer/TextEntrySeparator.java
Java Projects/TypingSpeedTest/recognizer/TextEntryWord.java
Java Projects/TypingSpeedTest/recognizer/TypingFlowMatcher.java

Typing Speed Test is added using java GUI
Close #4066

[ADDED]: Typing Speed Test

---

Java Projects/Text-File_Analyzer/Readme.md
Java Projects/Text-File_Analyzer/TextFileAnalyzer.java
Java Projects/Text-File_Analyzer/sample.txt

java program with sample text file

---

.github/workflows/analyze-pr-files.yml

feat: pr files analyzer feature to analyze graphical assets 🤖

---

Frontend-Projects/News_Homepage/styles.min.css

Frontend Project "News_Homepage" Navbar Space Correction
Close #3712 
**Before**
**After**

"News_Homepage" Navbar Space Correction

---

.github/workflows/auto-comment.yml

feat: auto comment feature to improve collabration ✨

---

Frontend-Projects/BTech Tea Shop/css/style.css
Frontend-Projects/BTech Tea Shop/index.html

The whole content and images resembles everything about coffee but the folder name is stating B.Tech Tea shop. Kindly, requesting you to change it to "B.Tech Coffee Shop". This is clearly the main owner who created the file has mistaken.
Close #3896 

Adding Content in Home & About us [B. Tech Tea Shop]

---

Frontend-Projects/Bus route booking system/index.html

Update index.html in Bus route Project

---

Devgeeks website/index.html
Devgeeks website/style.css

- I have added social buttons to the footer
- Made the home button in the footer take the user to the top of the webpage just like the other buttons do.
-  I have also fixed the image of Pranjay Poddar not displaying in the footer!
Close #3977 

[DevGeeks Website]: Added Social Buttons To Footer & Made Home Button Scroll To Top

---

Frontend-Projects/Attractive Food Ordering Website/index.html
Frontend-Projects/Attractive Food Ordering Website/script.js
Frontend-Projects/Attractive Food Ordering Website/style.css

Attractive Food Ordering Website
Issue #4038
Close #4038

Added Attractive Food Ordering Website [GSSOC'23]

---

Java Projects/Medical Prescription System/Prescription.java
Java Projects/Medical Prescription System/README.md

The Medical Prescription System is a Java application that allows users to enter their personal information, generate a prescription based on the given symptoms
Issue #4086
Close #4086 
@MohitGupta121 @TusharKesarwani  Sir kindly review the project and approved the PR

Medical Prescription System

---

Java Projects/Projectile Motion/Projectile.java
Java Projects/Projectile Motion/README.md

This is a Java program that simulates the motion of a projectile launched at an angle and initial velocity.
Close #4087 
@MohitGupta121 @TusharKesarwani @pranjay-poddar Sir kindly review the project and merged the pr

Enhance Projectile Motion Simulation (physics) JAVA

---

Custom Error Page/simple error page/404.html
Custom Error Page/simple error page/error.css

error page added

---

Js-Projects/n number calculator/sum.html

n sum calculator added

---

Frontend-Projects/Advice_Generator/style.css

[advice Generator] Homepage styling

---

Frontend-Projects/Anime_Pics_Generator/style.css

[anime pics] Card styling

---

Frontend-Projects/Apple Ecommerce/signup.html

Create signup.html for apple e-commerce site

---

Java Projects/GST Compliance/GST.java
Java Projects/GST Compliance/README.md

The GST Compliance Tracker is a Java application that helps you manage and track GST (Goods and Services Tax) transactions.
It allows you to add GST transactions, view all transactions, calculate total GST paid etc.
Issue number #4203 
Close #4203 
@MohitGupta121 @TusharKesarwani @pranjay-poddar  Sir kindly review the pr and merged it

GST Compliance Tracker in JAVA

---

Java Projects/Personal Expense tracker/Expense.java
Java Projects/Personal Expense tracker/README.md

The Personal Expense Tracker is a command-line Java application that helps you track your expenses and manage your personal finances.
Issue number #4249 
Close #4249 
@MohitGupta121 @TusharKesarwani @pranjay-poddar Sir kindly review the pr and merged it

Personal Expense Tracker

---

Repository_web_page/new/index.html
Repository_web_page/repository-statistics-generator.js
Repository_web_page/style.css

|||
|:----:|:---:|
| **BEFORE** | ![Screenshot 2023-07-27 at 08-25-50 Dev Geeks](https://github.com/pranjay-poddar/Dev-Geeks/assets/92252895/e092ebca-53f5-4125-a94d-09523b9c0ddf) | 
| **AFTER** | ![Screenshot 2023-07-27 at 08-10-50 Dev Geeks](https://github.com/pranjay-poddar/Dev-Geeks/assets/92252895/18cc2d9c-c050-48ad-bcb3-c26671b732f6) |

feat: live repository statistics fetch for dev-geeks webpage 🚀✨

---

Frontend-Projects/Contact manager app/index.html
Frontend-Projects/Contact manager app/script.js
Frontend-Projects/Contact manager app/style.css

Contact Manager App #3840 
Close #3840

Contact Manager App #3840

---

Animations-CSS/Search bar animation/index.html

Search Bar Animation #3841
Close #3841

Search Bar Animation #3841

---

Java Projects/Credit Risk Assessment/README.md
Java Projects/Credit Risk Assessment/credit.java

The Credit Risk Assessment program is a Java application that evaluates the credit risk of a customer based on their credit score, annual income, total debt, and years of credit history. 
Issue number #4248 
Close #4248 
@MohitGupta121 @TusharKesarwani @pranjay-poddar Sir kindly review the pr and merged it

Credit Risk Assessment in JAVA

---

Frontend-Projects/Image_Viewer/index.html
Frontend-Projects/Image_Viewer/main.js
Frontend-Projects/Image_Viewer/style.css

Image Viewer with link verifier #3343 
Close #3343

Image URL viewer Frontend Project

---

Frontend-Projects/Music_Player/index.html
Frontend-Projects/Music_Player/main.js
Frontend-Projects/Music_Player/song.js
Frontend-Projects/Music_Player/style.css

music player frontend Project #3344 
Close #3344

music player frontend Project

---

c_projects/Dudeney Number/Dudeney_Number.c
c_projects/Dudeney Number/ReadMe.md

Dudeney number

---

c_projects/Magic Number/ReadMe.md
c_projects/Magic Number/magic_number.c

magic number

---

Frontend-Projects/Animated_Login_Page/index.html
Frontend-Projects/Animated_Login_Page/style.css

[animated login] Home page styling

---

cpp-projects/Data Encryption Decryption/README.md
cpp-projects/Data Encryption Decryption/data.cpp

I make a the Caesar Cipher. It is a substitution cipher in which each letter in the plaintext is shifted a fixed number of positions down the alphabet. This program allows you to encrypt and decrypt messages using the Caesar Cipher with a specified shift value.
issue number #4278 
Close #4278 
@MohitGupta121 @TusharKesarwani Sir kindly review my project and merge the pr and please label the project level 2

Caesar Cipher Encryption and Decryption #4278

---

cpp-projects/G20_Renewable Energy/Energy.cpp
cpp-projects/G20_Renewable Energy/README.md

I make a the G20 Renewable Energy Knowledge Center . It is a command-line program written in C++ that provides information about renewable energy production in G20 countries. 
Issue number #4359 
Close #4359 
@MohitGupta121 @TusharKesarwani Sir kindly review my project and merge the pr and please label the project level 2

G20 Renewable Energy Knowledge Center in cpp

---

Js-Projects/scientific calculator/index.html
Js-Projects/scientific calculator/style.css

Scientific Calculator with 
Arithmetic  (+, -, *, /)
Trigonometric (sin, cos, tan)
Exponentials and logarithms (x^y, log, ln)
Mathematical constants (π, e)
Square root and power functions (x^2, x^3)
Factorial (x!)
Hyperbolic (sinh, cosh, tanh)
https://github.com/pranjay-poddar/Dev-Geeks/assets/74114936/220f4cac-7639-41d3-a53e-a9e8f2aceafc
Close #4376

Scientific Calculator

---

cpp-projects/Weather Station Dashboard/README.md
cpp-projects/Weather Station Dashboard/weather.cpp

I make a the Weather Station Dashboard. It is a simple command-line program that simulates real-time weather data for different locations and allows the user to view the weather data in both Celsius and Fahrenheit.
Issue number #4279 
Close #4279 
@MohitGupta121 @TusharKesarwani Sir kindly review my project and merge the pr

Weather Station Dashboard in Cpp

---

cpp-projects/Solar Energy Tracking System/README.md
cpp-projects/Solar Energy Tracking System/Solar.cpp

I make a the Solar Position Calculator . It is a C++ program that calculates various solar parameters based on a given geographic location (latitude and longitude) and date
Issue number #4276 
Close #4276 
@MohitGupta121 @TusharKesarwani Sir kindly review my project and merge the pr and please label the project level 2

Solar Position Calculator 

---

cpp-projects/Task Manager/README.md
cpp-projects/Task Manager/task.cpp

I make a task Manager is a command-line application written in C++ that allows users to manage tasks with their names and priorities. Users can add tasks, remove tasks, display the current task list, sort tasks by priority, save tasks to a file, and load tasks from a file.
Issue number #4275 
Close #4275 
@MohitGupta121 @TusharKesarwani Sir kindly review my project and merge the pr

Task Manager System in Cpp

---

cpp-projects/Hospital Management/Hospital/README.md
cpp-projects/Hospital Management/Hospital/code.cpp
cpp-projects/Hospital Management/README.md

Hospital Management System #4258 
Close #4258

Hospital Management [GSSOC'23]

---

Java Projects/DCF Valuation Model/README.md
Java Projects/DCF Valuation Model/Valuation.java

This is a Java program that performs a Discounted Cash Flow (DCF) valuation. The DCF valuation is a financial method used to estimate the value of an investment based on its future cash flows, discounted to their present value.
Issue number #4227 
Close #4227 
@MohitGupta121 @TusharKesarwani @pranjay-poddar Sir kindly review the pr and merged it

Discounted Cash Flow (DCF) Valuation Model

---

Python Projects/Video Processing/README.md
Python Projects/Video Processing/file.py

I've added the video-resolution altering script in python projects. It changes the resolution/scale of a video captured through the camera of user's device and modifys it's resolution according to the choice given by the user. 
- Load a video using cv2.VideoCapture()
- Create a VideoWriter object using cv2.VideoWriter()
- Extract frame by frame
- Resize the frames using cv2.set()
- Save the frames to a video file using cv2.VideoWriter()
- Release the VideoWriter and destroy all windows
Close #4259

Added Video Resolution Processing Application in Python

---

Python Projects/Socket Chat/README.md
Python Projects/Socket Chat/client.py
Python Projects/Socket Chat/server.py

This application creates a chatroom where client and server can connect to each other. This is done by creating a socket connection between the two, which has the capability to handle multiple threads.
Close #3389

Added Bluetooth Chatting application in python

---

Java Projects/System Information Viewer/README.md
Java Projects/System Information Viewer/system.java

I make a Java program that displays various system information, including CPU usage, memory usage, disk space, network statistics, CPU cores, and OS version.
Issue number #4201 
Close #4201 
@MohitGupta121 @TusharKesarwani Sir kindly review the project and please label gssoc'23 and level2

System Information Display in java

---

Animations-CSS/3d social media icons/index.html

3-d Social media icons #4404
Close #4404

3-d Social media icons

---

Navbars/Responsive sticky navbar/index.html
Navbars/Responsive sticky navbar/script.js
Navbars/Responsive sticky navbar/style.css

Responsive sticky navbar #4405 
Close #4405

Responsive sticky navbar

---

Frontend-Projects/Animated profile card/index.html
Frontend-Projects/Animated profile card/style.css

Animated Profile Card  #4402
Close #4402

Animated Profile Card

---

cpp-projects/hindu_scripture/README.md
cpp-projects/hindu_scripture/hindu.cpp
cpp-projects/hindu_scripture/texts/bhagavad_gita.txt
cpp-projects/hindu_scripture/texts/garg_samhita.txt
cpp-projects/hindu_scripture/texts/mahabharata.txt
cpp-projects/hindu_scripture/texts/ramayana.txt

Hindu Scriptures Reader
Issue number #4394 
Close #4394 

Hindu Scriptures Reader

---

cpp-projects/Load Shedding Simulator/Load.cpp
cpp-projects/Load Shedding Simulator/README.md

It is a C++ program that allows you to perform load shedding based on load forecasting and available power capacity. 
Issue number #4450 
Close #4450 

Load Shedding Simulator

---

cpp-projects/Tax Planning Recommendations system/README.md
cpp-projects/Tax Planning Recommendations system/taxplanning.cpp

It is a C++ program that provides tax planning recommendations based on the user's annual income and deductions.
Issue number #4392 
Close #4392 

Tax Planning Recommendations System

---

cpp-projects/Impact Assessment Tool/README.md
cpp-projects/Impact Assessment Tool/impact.cpp

Impact Assessment Tool
Issue number #4408 
Close #4408 

Impact Assessment Tool

---

cpp-projects/Movie Trivia Game/README.md
cpp-projects/Movie Trivia Game/game.cpp

I make a C++ program is a movie trivia game. It will ask the user a series of movie-related questions and check the user's answers against the correct answers. 
Issue number #4418 
Close #4418 

Movie Trivia Game

---

cpp-projects/Electrical Safety Calculator/Electrical.cpp
cpp-projects/Electrical Safety Calculator/README.md

It is a C++ program that allows you to perform safety calculations and checks for electrical circuits and loads. 
Issue number #4451 
Close #4451 

Electrical Safety Calculator

---

.vscode/settings.json
Frontend-Projects/2Circles loader/index.html
Frontend-Projects/2Circles loader/styles.css

I have added the project .Can it be merged now?
Close #4425

Circular preloader added

---

cpp-projects/Transformer Design/README.md
cpp-projects/Transformer Design/Transformer.cpp

It is a C++ application that allows you to design and analyze the parameters of a transformer based on user input. It calculates the turns ratio, core area, wire size, and efficiency of the transformer.
Issue number #4449 
Close #4449 

Transformer Design Calculation

---

Frontend-Projects/normal_loader/index.html
Frontend-Projects/normal_loader/styles.css

I have added the project .Can it be merged now?
Close #4424

Loading spinner added

---

cpp-projects/Rigid Body Physics Simulator/README.md
cpp-projects/Rigid Body Physics Simulator/rigid.cpp

It is a C++ program that simulates the physics of multiple rigid bodies in a 2D space. It include collision detection algorithms to handle collisions and resolves them using conservation of momentum and restitution. and advanced algorithms .
Issue number #4447 
Close #4447 

Rigid Body Physics Simulator

---

Python Projects/Income Tax Calculator/README.md
Python Projects/Income Tax Calculator/tax.py

It is a Python script that allows users to calculate their income tax based on predefined tax brackets. It provides a simple and easy-to-use interface for calculating income tax and gives users the option to save the tax calculation for future reference.
Issue number #4391 
Close #4391 

Income Tax Calculator

---

cpp-projects/Astrophysical Data Analysis/README.md
cpp-projects/Astrophysical Data Analysis/data.cpp

I make a  C++ program calculates various statistical measures for a set of astronomical data points. It provides functions to calculate the average, standard deviation, minimum, and maximum values of the data. Additionally, it offers the ability to remove outliers using sigma-clipping.
Issue number #4422 
Close #4422 

Astrophysical Data Analysis

---

cpp-projects/The Engineering Calculator Command-Line Tool/README.md
cpp-projects/The Engineering Calculator Command-Line Tool/calculator.cpp

I make a C++ program provides a simple command-line calculator with various engineering functionalities. It allows you to perform basic arithmetic operations, trigonometric functions, unit conversions, and vector operations.
Issue number #4419 
Close #4419 

Engineering Calculator Command-Line Tool

---

cpp-projects/Electrical Circuit Analyzer/README.md
cpp-projects/Electrical Circuit Analyzer/circuit.cpp

It is a C++ program that allows you to analyze electrical circuits consisting of resistors, capacitors, and inductors. 
Issue number #4448 
Close #4448 

Electrical Circuit Analyzer

---

Frontend-Projects/ring-roller animation/index.html
Frontend-Projects/ring-roller animation/styles.css

I have added the project .Can it be merged now?
Close #4423

Ring-roller added

---

Js-Projects/area calculator/area.html

area calculator added

---

Frontend-Projects/coding workshop website/index.html

coding workshop website added

---

Frontend-Projects/hirecoder/final.html

personal coder website added

---

Frontend-Projects/religious website/index.html
Frontend-Projects/religious website/styl.css
Frontend-Projects/religious website/style.css

Close #4068 
video reference:
[Screencast from 25-07-23 11:27:31 PM IST.webm](https://github.com/pranjay-poddar/Dev-Geeks/assets/104543751/ae88a531-4b09-4b80-b428-b97d3cd7482f)

religious website added

---

Python Projects/Attendances/README.md
Python Projects/Attendances/main.py

I've added the college attendance system, which can be used to display and keep track of each subject added by the user.It also uses the SMTP to send mails to students regarding their attendance.
Close #3163

Added College Attendance System in Python

---

Frontend-Projects/Restaurant site/CSS/style.css
Frontend-Projects/Restaurant site/about.html
Frontend-Projects/Restaurant site/contact.html
Frontend-Projects/Restaurant site/homepage.html
Frontend-Projects/Restaurant site/menu.html

Made the navbar of the website stick to top for all html files and made them scroll smoothly when clicked on  the respective buttons in navbar
Close #4361

Restaurant Site: Stick NavBar to top and made the website scroll smoothly

---

Java Projects/Bank Management/BankManagementSystem.java
Java Projects/Bank Management/README.md

Using oops concepts and dsa concepts(linkedlist, Trie)

---

Js-Games/Pong Game/ball.js
Js-Games/Pong Game/index.html
Js-Games/Pong Game/paddle.js
Js-Games/Pong Game/script.js
Js-Games/Pong Game/style.css

Pong game added

---

Animations-CSS/Box Dog animation/README.md
Animations-CSS/Box Dog animation/index.html
Animations-CSS/Box Dog animation/style.css

Box dog animation[GSSOC'23]

---

Frontend-Projects/Gym website/style.css

Fixed the nabar to the top and made the website scroll smoothly.
Close #4363 

[Gym Website]: Fixed navbar to top & website scroll smoothly

---

cpp-projects/Mathscape Master/MathScape.cpp
cpp-projects/Mathscape Master/README.md

added more features to mathscape master 

---

cpp-projects/PhysiTech/PhysiTech.cpp
cpp-projects/PhysiTech/README.md

added mechanics materials to physitech

---

cpp-projects/Algorithm_learner/README.md
cpp-projects/Algorithm_learner/algo.cpp

Updated Algorithm learner C++

---

Animations-CSS/Folded_list/Readme.md
Animations-CSS/Folded_list/index.html
Animations-CSS/Folded_list/style.css

Folded List with Css 
Close #3872

Folded list with Css (#3872)

---

ML Projects/IPL Prediction/IPLPrediction.ipynb

IPL Score prediction ML Model: Uses Lasso Regression + GridSearchCV  to predict final score by historical IPL match data.
Close #4377

IPL Score prediction ML Model

---

Frontend-Projects/Salon Site/README.md

Adding Readme file to Salon site

---

ML Projects/Stress Detection Project/README.md

Added README.md file for ML Project

---

Java Projects/Employee Management System - CRUD Operations/README.md
Java Projects/Employee Management System - CRUD Operations/bean/Employee.java
Java Projects/Employee Management System - CRUD Operations/dao/EmployeeDao.java
Java Projects/Employee Management System - CRUD Operations/dao/EmployeeDaoImpl.java
Java Projects/Employee Management System - CRUD Operations/factory/ConnectionFactory.java
Java Projects/Employee Management System - CRUD Operations/factory/EmployeeDaoFactory.java
Java Projects/Employee Management System - CRUD Operations/factory/EmployeeServiceFactory.java
Java Projects/Employee Management System - CRUD Operations/service/EmployeeService.java
Java Projects/Employee Management System - CRUD Operations/service/EmployeeServiceImpl.java
Java Projects/Employee Management System - CRUD Operations/test/jdbcLayeredApp.java

Added Employee Management System Project- CRUD Operations [GSSOC' 23]  #2745

---

Java Projects/PassCraft/PassCraft.java
Java Projects/PassCraft/readme.md

I want to add a new project called PassCraft in Java Projects folder #2975
Close #2975

Adding PassCraft in Java Projects

---

Python Projects/Phone-Number/README.md
Python Projects/Phone-Number/main.py

Phone number detail provider #3726 
Please merge this PR as soon as possible.

Add new project => phone number details provider

---

ML Projects/Reddit-Sentiment-Analysis-using-Pytorch-main/README.md
ML Projects/Reddit-Sentiment-Analysis-using-Pytorch-main/reddit-sentiment-analysis.ipynb

Reddit sentiment analysis using pytorch #2619 
Close #<2619>

Added reddit-sentiment analysis using pytorch

---

Frontend-Projects/Responsive login form/index.html
Frontend-Projects/Responsive login form/style.css

Responsive Login Form  #4536 
Close #4536

Responsive Login Form 

---

cpp-projects/Forest Health Monitoring/README.md
cpp-projects/Forest Health Monitoring/health.cpp

Forest health Monitoring System Added
Issue number #4552 
Close #4552 
@MohitGupta121 @TusharKesarwani Sir kindly review the pr and merged the pr

Forest health Monitoring System

---

Python Projects/CHILD VACCINATION MANAGEMENT SYSTEM/README.md
Python Projects/CHILD VACCINATION MANAGEMENT SYSTEM/main.py

Child Vaccination Management System helps parents book vaccination appointments for their children with just a few clicks.
This is a simple Python program that allows users to manage vaccination records for children. The program uses the pickle module to serialize and deserialize Python objects, storing and retrieving vaccination data in a binary file.
Close #4525

[Adding a new project]: CHILD VACCINATION MANAGEMENT USING PYTHON [gssoc23]

---

ML Projects/Fashion-recommender-system/README.md
ML Projects/Fashion-recommender-system/app.py
ML Projects/Fashion-recommender-system/dataset
ML Projects/Fashion-recommender-system/main.py
ML Projects/Fashion-recommender-system/test.py

Added a Deep Learning based Fashion Recommender System using the ResNET50 , it's a Clothes Recommendation or an Ecommerce Project using machine learning techniques.
Close #3944 
Screenshot:-
- [Yes] I have mentioned the issue number in my Pull Request.
- [Yes] I have commented my code, particularly in hard-to-understand areas
- [Yes] I have created a helpful and easy to understand `README.md`

[GSSoc'23] Added fashion-recommender-system #3944

---

ML Projects/Posture detection/README.md
ML Projects/Posture detection/index.html
ML Projects/Posture detection/sketch.js

This project aims to detect the body posture using (posenet demo built using ml5.js)
Close #3945 
screenshot:-
- [Yes] I have mentioned the issue number in my Pull Request.
- [YEs] I have commented my code, particularly in hard-to-understand areas
- [Yes] I have created a helpful and easy to understand `README.md`

Added Posture detection using PoseNet #3945

---

Machine Learning Model - Deployment/Game-of-throne-personality-matcher/Dataset
Machine Learning Model - Deployment/Game-of-throne-personality-matcher/README.md
Machine Learning Model - Deployment/Game-of-throne-personality-matcher/app.py
Machine Learning Model - Deployment/Game-of-throne-personality-matcher/got.ipynb
Machine Learning Model - Deployment/Game-of-throne-personality-matcher/mnist.ipynb

Added  Game-of-thrones-personality-matcher, this project aims to find Similar Game of Thrones Character using Machine Learning and Visualizing High Dimensional Data.
Close #4088 
Screenshot of model:-
- [Yes] I have mentioned the issue number in my Pull Request.
- [Yes] I have commented my code, particularly in hard-to-understand areas
- [Yes] I have created a helpful and easy to understand `README.md`

[GSSoc'23] Added Game-of-thrones-personality-matcher #4088

---

cpp-projects/Forest Climate Change Impact Assessment/README.md
cpp-projects/Forest Climate Change Impact Assessment/forest_impact.cpp

Forest Climate change Impact Assessment Added
Issue number #4556 
Close #4556 
@MohitGupta121 @TusharKesarwani Sir kindly review the pr and merged the pr

Forest Climate change Impact Assessment

---

cpp-projects/Forest Carbon Sequestration Calculator/README.md
cpp-projects/Forest Carbon Sequestration Calculator/carbon_calculator.cpp

Forest Carbon Sequestration Calculator Added
Issue number #4554 
Close #4554 
@MohitGupta121 @TusharKesarwani Sir kindly review the pr and merged the pr

Forest Carbon Sequestration Calculator

---

Frontend-Projects/Events website/index.html

Events booking website
Close #4058

Events Booking website

---

Frontend-Projects/Painting/index.html
Frontend-Projects/Painting/main.js
Frontend-Projects/Painting/style.css

Painting app frontend project #3340 
Close #3340

Painting app frontend project

---

Frontend-Projects/ImageEditor/index.html
Frontend-Projects/ImageEditor/main.js
Frontend-Projects/ImageEditor/style.css

Added image editor frontend project #3341 
Close #3341

Added image editor frontend project

---

Frontend-Projects/Google clone/index.html
Frontend-Projects/Google clone/style.css

Google clone added frontend Project #3342 
Close #3342

Google clone added frontend Project

---

Frontend-Projects/Fylo_landing_page/Readme.md
Frontend-Projects/Fylo_landing_page/index.html
Frontend-Projects/Fylo_landing_page/style.css

code fylo_landing_page #4049

---

Frontend-Projects/Feedback_UI/README.md
Frontend-Projects/Feedback_UI/index.html
Frontend-Projects/Feedback_UI/index.js
Frontend-Projects/Feedback_UI/styles.css

code feedback #4048

---

Js-Games/cut_the_Rope/Readme.md
Js-Games/cut_the_Rope/css/style.css
Js-Games/cut_the_Rope/index.html
Js-Games/cut_the_Rope/js/script.js

code cuttherope #3490

---

Python Projects/qrCodeGenerator/main.py

A qr code generator
This PR closes #3509 

New project qr code generator

---

Frontend-Projects/World Information Website/README.md
Frontend-Projects/World Information Website/index.html
Frontend-Projects/World Information Website/script.js
Frontend-Projects/World Information Website/style.css

World Info Website and the issue no is 2130
Close #2130

World Informaiton Website

---

Animations-CSS/Caterpillar_loader/Readme.md
Animations-CSS/Caterpillar_loader/index.html
Animations-CSS/Caterpillar_loader/style.css

Caterpillar loader with css animation 
Close #3871

Caterpillar loader (#3871)

---

cpp-projects/Credit-card-validator/Credit_card.cpp
cpp-projects/Credit-card-validator/README.md

Credit Card validator completed #3870

---

Frontend-Projects/Typing Speed Test Website/README.md
Frontend-Projects/Typing Speed Test Website/index.html
Frontend-Projects/Typing Speed Test Website/script.js
Frontend-Projects/Typing Speed Test Website/style.css

Typing Speed Test Website

---

Frontend-Projects/note_app/Readme.md
Frontend-Projects/note_app/css/custom.css
Frontend-Projects/note_app/index.html
Frontend-Projects/note_app/js/app.js

code note_app #4106

---

ML Projects/PDF to TXT/Converter.py
ML Projects/PDF to TXT/GUI.py

Close #1411 
Earlier While Running the code its showing the error , I have resolved it and created a GUI for the same using python tkinter library.

[GSSOC'23] Solved Issue #1411 and Created a GUI for PDF to TEXT Converter

---

Java Projects/Tower of Hanoi/Hanoi.java
Java Projects/Tower of Hanoi/README.md

Tower of Hanoi  #4230 
Close #4230

Tower of Hanoi [GSSOC'23]

---

Python Projects/gif converter/gif.py

GIF Converter (GUI) in Python
https://github.com/pranjay-poddar/Dev-Geeks/assets/74114936/d19d62e9-e495-4db8-b5fe-1e92d7328f22
Close #4579

GIF Converter in Python

---

Animations-JS/Countdown timer/ReadMe.md
Animations-JS/Countdown timer/countdown.html
Animations-JS/Countdown timer/script.js
Animations-JS/Countdown timer/style.css

Countdown timer animation

---

Python Projects/Video Reversal/ReadMe.md
Python Projects/Video Reversal/video_reversing.py

video reversing

---

Animations-CSS/Slanted Menu Design/README.md
Animations-CSS/Slanted Menu Design/index.html
Animations-CSS/Slanted Menu Design/styles.css

Successfully added an Animation using CSS about a slanted menu.
Close #4636

Added Slanted Menu CSS Animation

---

cpp-projects/Commodity Price Monitor/.vscode/settings.json
cpp-projects/Commodity Price Monitor/README.md
cpp-projects/Commodity Price Monitor/commodity.cpp

Commodity Price Monitor Added
Issue number #4511 
Close #4511 

Commodity Price Monitor

---

Js-Projects/Real-Time Chat Application/README.md
Js-Projects/Real-Time Chat Application/index.html
Js-Projects/Real-Time Chat Application/script.js
Js-Projects/Real-Time Chat Application/style.css

The Real-Time Chat Application is a web-based platform that enables users to communicate with each other in real-time using text messages. It provides a seamless and interactive chatting experience, fostering instant communication and collaboration between users. The application utilizes HTML, CSS, and JavaScript to create an attractive and user-friendly interface.
Close #4671

[Add a new project] Real-Time Chat Application. [gssoc23]

---

Python Projects/StackOverflow Scraper/README.md
Python Projects/StackOverflow Scraper/questions.py

StackOverflow Scraper
Close #3981

StackOverflow Scraper added

---

Frontend-Projects/Dental website/index.html

Blog Section updated

---

Frontend-Projects/Candies_Website/index.html

Candies Content added

---

Frontend-Projects/business header/contact.html
Frontend-Projects/business header/index.html

Contact section added

---

cpp-projects/Blast Vibration Analysis/README.md
cpp-projects/Blast Vibration Analysis/blast.cpp

Blast Vibration Analysis Added
Issue number #4631 
Close #4631 
@TusharKesarwani Sir kindly  review my pr

Blast Vibration Analysis

---

cpp-projects/Rock Mass Classification System/README.md
cpp-projects/Rock Mass Classification System/rock.cpp

Rock Mass Classification System Added
issue number #4626 
Close #4626 

Rock Mass Classification System

---

cpp-projects/Chemical Element Properties/README.md
cpp-projects/Chemical Element Properties/chemical.cpp

Chemical Element Properties Added
Issue number #4625 
Close #4625 

Chemical Element Properties

---

cpp-projects/Chemical Reactor Design/README.md
cpp-projects/Chemical Reactor Design/reactor.cpp

Chemical Reactor Design Added
Issue number #4624 
Close #4624 

Chemical Reactor Design

---

cpp-projects/Polymer Molecular Weight Calculator/README.md
cpp-projects/Polymer Molecular Weight Calculator/polymer.cpp

Polymer Molecular Weight Calculator Added
Issue number #4629 
Close #4629 

Polymer Molecular Weight Calculator

---

cpp-projects/Ore Grade Analysis/README.md
cpp-projects/Ore Grade Analysis/ore_grade.cpp

Ore Grade Analysis Added
Issue number #4632 
Close #4632 

Ore Grade Analysis

---

Animations-CSS/Pulse animation/ReadMe.md
Animations-CSS/Pulse animation/index.html
Animations-CSS/Pulse animation/style.css

pulse effect animation

---

c_projects/strong number/ReadMe.md
c_projects/strong number/strong_number.c

strong number

---

Python Projects/Day-finder/Day-Finder.py

Python Project Tells you day on which you born #4541
Close #4541

Python Project Tells you day on which you born #4541

---

Frontend-Projects/Encoder Decoder/index.html
Frontend-Projects/Encoder Decoder/script.js
Frontend-Projects/Encoder Decoder/styles.css

URL Encoder Decoder Project #4728
Close #4728

URL Encoder Decoder Project Added #4728

---

Animations-JS/Code-Generator-Animation/README.md
Animations-JS/Code-Generator-Animation/index.html
Animations-JS/Code-Generator-Animation/script.js
Animations-JS/Code-Generator-Animation/style.css

Title - Code Generator Anime
Issue Number - 4428
Close #4428

[GSSoC'23] Code Animation Project Ready

---

Frontend-Projects/Gym-Landing Page/index.html

Gym Landing Page Navbar Alignment
I had Fixed the navbar alignment
Close #4460

navbar alignment fixed for gym landing page

---

Frontend-Projects/Notification UI/index.html
Frontend-Projects/Notification UI/style.css

Notification Template Frontend Project #4835
Close #4835

Added Notification Template Frontend Project #4835

---

Frontend-Projects/Compare Template/index.html
Frontend-Projects/Compare Template/style.css

Frontend Project Compare Page Template #4806
Close #4806

Added Frontend Project Compare Page Template #4806

---

cpp-projects/Heat Transfer Simulation/README.md
cpp-projects/Heat Transfer Simulation/heat.cpp

Heat Transfer Simulation Added
Issue number #4630 
Close #4630 
@TusharKesarwani Sir kindly review my project

Heat Transfer Simulation

---

Python Projects/Reddit Scraper/main.py
Python Projects/Reddit Scraper/soup_scraper.py

I've added the reddit web scraper. It has two different files: one file ```main.py``` uses selenium where as other file ```soup_scraper.py``` uses BeautifulSoup to scrape data from reddit. It is capable of scraping every major data from reddit, including profile IDs, posts on a specific topic, and so on. 
Close #4761

Added Reddit web scraper project

---

Frontend-Projects/Project-WebPage/contact.html
Frontend-Projects/Project-WebPage/index.html
Frontend-Projects/Project-WebPage/roadmap.html
Frontend-Projects/Project-WebPage/style/contact.css
Frontend-Projects/Project-WebPage/style/style.css

Animated Frontend Project #4840
Close #4840

Frontend Project added Standard webpage MetaVerse

---

cpp-projects/Language Translation/README.md
cpp-projects/Language Translation/french.cpp

Language Translation Added
Issue number #4628 
Close #4628 
@TusharKesarwani Sir kindly review my project

Language Translation

---

Js-Games/Plus Minus/index.html

I've added the plus-minus game in javascript projects. This game is a 2-d board game where user's task is to make every row or column's sum equal to zero. 
Close #4754

Added Plus-Minus Javascript Game

---

Python Projects/Pixaby Scraper/__init__.py
Python Projects/Pixaby Scraper/main.py

I've added the pixabay web scraper. It scrapes and stores the images from pixabay directly into the user's account. User can query anything using the relevant functions from the scraper class. 
Close #4759

Added Pixaby web scraper project

---

VirusDetector/README.md
VirusDetector/modelPerf.ipynb
VirusDetector/verify.py

- ### Virus Detector - #4866 
Hello @MohitGupta121 , @TusharKesarwani ,
I have added a Malware/Virus Detector which can we used to detect malware or virus in the PC or Laptop with the Help of Py3 I have developed this Project.
```cmake
Good label will really appreciated
```

Added Malware/Virus Detector

---

Animations-CSS/Rainy clouds/ReadMe.md
Animations-CSS/Rainy clouds/index.html
Animations-CSS/Rainy clouds/style.css

Rainy clouds animation

---

cpp-projects/Souvenir Shopping Assistant/README.md
cpp-projects/Souvenir Shopping Assistant/SHOPPING.cpp

Souvenir Shopping Assistant Added
Issue number #4627 
Close #4627 

Souvenir Shopping Assistant

---

Frontend-Projects/Encipher_Decipher/README.md
Frontend-Projects/Encipher_Decipher/crypter-css.css
Frontend-Projects/Encipher_Decipher/decrypter-js.js
Frontend-Projects/Encipher_Decipher/decrypter.html
Frontend-Projects/Encipher_Decipher/encrypter.html
Frontend-Projects/Encipher_Decipher/encrypter.js
Frontend-Projects/Encipher_Decipher/index-css.css
Frontend-Projects/Encipher_Decipher/index.html

Successfully renamed "Encipher I Decipher" to "Encipher_Decipher" to fix the cloning issue.
Close #4748 

[Bug Fix] Renamed Project To Fix Cloning Issue

---

Animations-CSS/Bouncing ball/ReadMe.md
Animations-CSS/Bouncing ball/index.html
Animations-CSS/Bouncing ball/style.css

bouncing ball animation

---

Js-Games/Piano Tiles/index.html
Js-Games/Piano Tiles/script.js
Js-Games/Piano Tiles/styles.css

Title : Piano Tiles Game [GSSOC'23]
Issue Number : #3671
Close #3671

Piano Tiles Game

---

Frontend-Projects/E-mart/about.html
Frontend-Projects/E-mart/contact.html
Frontend-Projects/E-mart/index.file
Frontend-Projects/E-mart/products.html

E-mart Site 

---

Frontend-Projects/Qwickstay/contact.html
Frontend-Projects/Qwickstay/index.html
Frontend-Projects/Qwickstay/login.html
Frontend-Projects/Qwickstay/search.html

QwickStay Project added

---

cpp-projects/Spacecraft Orbital Mechanics Simulator/README.md
cpp-projects/Spacecraft Orbital Mechanics Simulator/oribital.cpp

Spacecraft Orbital Mechanics Simulator Added
Issue number #4723 
Close #4723 

Spacecraft Orbital Mechanics Simulator

---

cpp-projects/Terrain Elevation Profile Generator/README.md
cpp-projects/Terrain Elevation Profile Generator/profile.cpp

Terrain Elevation Profile Generator Added
Issue number #4722 
Close #4722 
@MohitGupta121 @TusharKesarwani Sir kindly  please review the pr

Terrain Elevation Profile Generator

---

cpp-projects/Startup Metrics Dashboard/README.md
cpp-projects/Startup Metrics Dashboard/metrics.txt
cpp-projects/Startup Metrics Dashboard/startup.cpp

Issue number #4719 
Close #4719 
@MohitGupta121 @TusharKesarwani Sir kindly please review the pr

Startup Metrics Dashboard

---

cpp-projects/Startup Pitch Generator/README.md
cpp-projects/Startup Pitch Generator/pitch.cpp

Startup Pitch Generator Added
Issue number #4718 
Close #4718 
@MohitGupta121 @TusharKesarwani Sir kindly please review the pr

Startup Pitch Generator

---

cpp-projects/Aircraft Maintenance System/README.md
cpp-projects/Aircraft Maintenance System/aircraft.cpp

Aircraft Maintenance System Added
Issue number #4721 
Close #4721 

Aircraft Maintenance System

---

Arduino Projects/Line Follower bot/README.md
Arduino Projects/Line Follower bot/main.cpp

This projcets presents the source code of a line follower bot. Loading this code into the memory of microcontroller makes it run crazy after a line. 
Close #4861

Added Line follower robot code 

---

Js-Games/Bean Stash/README.md
Js-Games/Bean Stash/index.html

Added the game to the ```Js-Projects``` folder. It is a javascript multiplayer game in which the task of players is to transact and gain as much beans as possible in the give  time.
Close #4859

Added bean-stash multiplayer game

---

Python Projects/Weight Conversion(GUI)/app.py

In this program, we'll provide options for converting weight from one unit to another (e.g., kilograms to pounds, pounds to kilograms)
https://github.com/pranjay-poddar/Dev-Geeks/assets/74114936/f9321186-adb9-4c77-aab2-5f6d8995d8ae
Close #4457

Weight Conversion program in python(GUI) 

---

cpp-projects/SMS Scheduler/README.md
cpp-projects/SMS Scheduler/sms.cpp

SMS Scheduler Utility Added
Issue number #4801 
Close #4801 
@TusharKesarwani Sir kindly please review the pr

SMS Scheduler Utility

---

cpp-projects/Modem Configuration Utility/README.md
cpp-projects/Modem Configuration Utility/modem.cpp

Modem Configuration Utility Added
Issue number #4800 
Close #4800 
@TusharKesarwani Sir kindly please review the pr

 Modem Configuration Utility

---

cpp-projects/Tax Filing System/README.md
cpp-projects/Tax Filing System/tax.cpp

Tax Filling System Added
Issue number #4742 
Close #4742 
@TusharKesarwani Sir kindly please review the pr

Tax Filling System

---

cpp-projects/Product Roadmap Generator/README.md
cpp-projects/Product Roadmap Generator/product.cpp

Product Roadmap Generator Added
Issue number #4717 
Close #4717 
@MohitGupta121 @TusharKesarwani Sir kindly please review the pr

Product Roadmap Generator

---

cpp-projects/Molecular Weight Calculator/README.md
cpp-projects/Molecular Weight Calculator/moleculor.cpp

Molecular Weight Calculator Added
Issue number #4676 
Close #4676 

Molecular Weight Calculator

---

Js-Games/chrome_dino_game/Readme.md
Js-Games/chrome_dino_game/cactus.js
Js-Games/chrome_dino_game/dino.js
Js-Games/chrome_dino_game/ground.js
Js-Games/chrome_dino_game/index.html
Js-Games/chrome_dino_game/script.js
Js-Games/chrome_dino_game/styles.css
Js-Games/chrome_dino_game/updateCustomProperty.js

code chrome_dino_game #4221

---

cpp-projects/Mortgage Calculator/README.md
cpp-projects/Mortgage Calculator/mortage.cpp

Mortgage Calculator Added
Issue number #4741 
Close #4741 
@TusharKesarwani Sir kindly please review the pr

Mortgage Calculator

---

Frontend-Projects/stopwatch/README.md
Frontend-Projects/stopwatch/index.html
Frontend-Projects/stopwatch/index.js
Frontend-Projects/stopwatch/styles.css

code stopwatch #4745

---

Frontend-Projects/paintry login page/aboutus.html

Changing Button Size
Close  #3948
Earlier
Now
https://github.com/pranjay-poddar/Dev-Geeks/assets/127978268/cac14b90-5de9-489d-b296-793157647dbd

Change in Button Size in Paintry login page

---

Js-Projects/Name-Generator/README.md
Js-Projects/Name-Generator/css/responsive.css
Js-Projects/Name-Generator/css/style.css
Js-Projects/Name-Generator/index.html
Js-Projects/Name-Generator/script.js

Title - Name Generator Application
Issue Number - 4689
Close #4689

[GSSoC'23] Name Generator Application Ready

---

Js-Projects/World_Countries_Data_Query_Visualizing_Js_Project/index.html
Js-Projects/World_Countries_Data_Query_Visualizing_Js_Project/scripts/main.js
Js-Projects/World_Countries_Data_Query_Visualizing_Js_Project/styles.css

add: world countries visualizing js project 🌐✨ 

---

cpp-projects/Waste Sorting Simulator/README.md
cpp-projects/Waste Sorting Simulator/waste.cpp

Waste Sorting Simulator Added
Issue number #5023 
Close #5023 
@MohitGupta121 @TusharKesarwani Sir kindly review these pr

Waste Sorting Simulator

---

Python Projects/AskUbuntu Scraper/README.md
Python Projects/AskUbuntu Scraper/questions.py

The askUbuntu scraper will retrieve various details from the ask Ubuntu website, including questions, views, votes, answer counts, and descriptions in JSON format.
Close #3982

added Ask ubuntu Scraper
